// al_and9d: 6-stage AND-rotation cascade (generated by Track 3 wave-9)
#include <stdint.h>

static inline uint64_t rotl64(uint64_t x, unsigned r) {
    r &= 63;
    return r ? (x << r) | (x >> (64 - r)) : x;
}

uint64_t mix_hash(uint64_t v, uint64_t k) {
    uint64_t x = v ^ k;
    x = x ^ (rotl64(x, 3) & rotl64(x, 7)) ^ rotl64(x, 19);  // stage 0
    x = x ^ (rotl64(x, 5) & rotl64(x, 14)) ^ rotl64(x, 11);  // stage 1
    x = x ^ (rotl64(x, 7) & rotl64(x, 20)) ^ rotl64(x, 23);  // stage 2
    x = x ^ (rotl64(x, 9) & rotl64(x, 24)) ^ rotl64(x, 13);  // stage 3
    x = x ^ (rotl64(x, 11) & rotl64(x, 38)) ^ rotl64(x, 17);  // stage 4
    x = x ^ (rotl64(x, 13) & rotl64(x, 47)) ^ rotl64(x, 7);  // stage 5
    x = x ^ rotl64(k, 13);
    return x;
}
