// al_and9d: 6-stage AND-rotation cascade (generated by Track 3 wave-9)
module al_and9d(
    input [63:0] val,
    input [63:0] key,
    output [63:0] out
);
    wire [63:0] x0 = val ^ key;
    wire [63:0] s0a = {x0[60:0], x0[63:61]};
    wire [63:0] s0b = {x0[56:0], x0[63:57]};
    wire [63:0] s0c = {x0[44:0], x0[63:45]};
    wire [63:0] x1 = x0 ^ (s0a & s0b) ^ s0c;
    wire [63:0] s1a = {x1[58:0], x1[63:59]};
    wire [63:0] s1b = {x1[49:0], x1[63:50]};
    wire [63:0] s1c = {x1[52:0], x1[63:53]};
    wire [63:0] x2 = x1 ^ (s1a & s1b) ^ s1c;
    wire [63:0] s2a = {x2[56:0], x2[63:57]};
    wire [63:0] s2b = {x2[43:0], x2[63:44]};
    wire [63:0] s2c = {x2[40:0], x2[63:41]};
    wire [63:0] x3 = x2 ^ (s2a & s2b) ^ s2c;
    wire [63:0] s3a = {x3[54:0], x3[63:55]};
    wire [63:0] s3b = {x3[39:0], x3[63:40]};
    wire [63:0] s3c = {x3[50:0], x3[63:51]};
    wire [63:0] x4 = x3 ^ (s3a & s3b) ^ s3c;
    wire [63:0] s4a = {x4[52:0], x4[63:53]};
    wire [63:0] s4b = {x4[25:0], x4[63:26]};
    wire [63:0] s4c = {x4[46:0], x4[63:47]};
    wire [63:0] x5 = x4 ^ (s4a & s4b) ^ s4c;
    wire [63:0] s5a = {x5[50:0], x5[63:51]};
    wire [63:0] s5b = {x5[16:0], x5[63:17]};
    wire [63:0] s5c = {x5[56:0], x5[63:57]};
    wire [63:0] x6 = x5 ^ (s5a & s5b) ^ s5c;
    wire [63:0] kr = {key[50:0], key[63:51]};
    assign out = x6 ^ kr;
endmodule
