// hyb12_sand2a: 2xAND + S-box + 2xAND (triplets 3-4) + L(5,13): interleaved heterogeneous (generated by hybrid/codesign/gen_batch12.py)
#include <stdint.h>
static inline uint64_t rotl64(uint64_t x, int r) {
    r &= 63;
    return r ? (x << r) | (x >> (64 - r)) : x;
}
static const uint8_t SBOX[16] = {0,1,2,3,4,6,8,11,13,9,7,15,12,10,5,14};
static inline uint64_t sbox64(uint64_t x) {
    uint64_t y = 0;
    for (int i = 0; i < 16; i++)
        y |= (uint64_t)SBOX[(x >> (4*i)) & 0xFu] << (4*i);
    return y;
}
static inline uint64_t lin513(uint64_t x) {
    return x ^ rotl64(x, 5) ^ rotl64(x, 13);
}
uint64_t mix_hash(uint64_t val, uint64_t key) {
    uint64_t x = val ^ key;
    { /* AND stage 0: (1,2,13) */
        uint64_t ra = rotl64(x, 1), rb = rotl64(x, 2), rc = rotl64(x, 13);
        x ^= (ra & rb) ^ rc;
    }
    { /* AND stage 1: (7,19,5) */
        uint64_t ra = rotl64(x, 7), rb = rotl64(x, 19), rc = rotl64(x, 5);
        x ^= (ra & rb) ^ rc;
    }
    x = sbox64(x);
    { /* AND stage 2: (3,11,29) */
        uint64_t ra = rotl64(x, 3), rb = rotl64(x, 11), rc = rotl64(x, 29);
        x ^= (ra & rb) ^ rc;
    }
    { /* AND stage 3: (17,31,7) */
        uint64_t ra = rotl64(x, 17), rb = rotl64(x, 31), rc = rotl64(x, 7);
        x ^= (ra & rb) ^ rc;
    }
    x = lin513(x);
    x ^= rotl64(key, 13);
    return x;
}
