// cd1_p_a21b7_l513_nw: hybrid 4r SPN
// GENERATED by hybrid/gen_hybrid.py -- do not edit by hand.
module cd1_p_a21b7_l513_nw(
    input  [63:0] val,
    input  [63:0] key,
    output [63:0] out
);
    // S-box as case statements per nibble would go here;
    // for S0 synthesis we use a behavioral model
    reg [63:0] x;
    reg [63:0] rk;
    reg [63:0] t, p, l;
    integer i, r;
    function [3:0] sbox4(input [3:0] v);
        case (v)
            4'd0: sbox4 = 4'd0;
            4'd1: sbox4 = 4'd1;
            4'd2: sbox4 = 4'd2;
            4'd3: sbox4 = 4'd3;
            4'd4: sbox4 = 4'd4;
            4'd5: sbox4 = 4'd6;
            4'd6: sbox4 = 4'd8;
            4'd7: sbox4 = 4'd11;
            4'd8: sbox4 = 4'd13;
            4'd9: sbox4 = 4'd9;
            4'd10: sbox4 = 4'd7;
            4'd11: sbox4 = 4'd15;
            4'd12: sbox4 = 4'd12;
            4'd13: sbox4 = 4'd10;
            4'd14: sbox4 = 4'd5;
            4'd15: sbox4 = 4'd14;
            default: sbox4 = 4'd0;
        endcase
    endfunction
    function [63:0] rotl64(input [63:0] v, input [5:0] r);
        rotl64 = (v << r) | (v >> (6'd64 - r));
    endfunction
    always @(*) begin
        x = val;
        for (r = 0; r < 4; r = r + 1) begin
            // round key
            rk = rotl64(key, 13*(r+1));
            case (r)
                0: rk = rk ^ 64'h9E3779B97F4A7C15;
                1: rk = rk ^ 64'h3C6EF372FE94F82A;
                2: rk = rk ^ 64'hDAA66D2C7DDF743F;
                3: rk = rk ^ 64'h78DDE6E5FD29F054;
            endcase
            // S-box layer
            t = x ^ rk;
            for (i = 0; i < 16; i = i + 1)
                t[4*i +: 4] = sbox4(t[4*i +: 4]);
            // P-box layer
            p = 64'd0;
            p[7] = t[0];
            p[28] = t[1];
            p[49] = t[2];
            p[6] = t[3];
            p[27] = t[4];
            p[48] = t[5];
            p[5] = t[6];
            p[26] = t[7];
            p[47] = t[8];
            p[4] = t[9];
            p[25] = t[10];
            p[46] = t[11];
            p[3] = t[12];
            p[24] = t[13];
            p[45] = t[14];
            p[2] = t[15];
            p[23] = t[16];
            p[44] = t[17];
            p[1] = t[18];
            p[22] = t[19];
            p[43] = t[20];
            p[0] = t[21];
            p[21] = t[22];
            p[42] = t[23];
            p[63] = t[24];
            p[20] = t[25];
            p[41] = t[26];
            p[62] = t[27];
            p[19] = t[28];
            p[40] = t[29];
            p[61] = t[30];
            p[18] = t[31];
            p[39] = t[32];
            p[60] = t[33];
            p[17] = t[34];
            p[38] = t[35];
            p[59] = t[36];
            p[16] = t[37];
            p[37] = t[38];
            p[58] = t[39];
            p[15] = t[40];
            p[36] = t[41];
            p[57] = t[42];
            p[14] = t[43];
            p[35] = t[44];
            p[56] = t[45];
            p[13] = t[46];
            p[34] = t[47];
            p[55] = t[48];
            p[12] = t[49];
            p[33] = t[50];
            p[54] = t[51];
            p[11] = t[52];
            p[32] = t[53];
            p[53] = t[54];
            p[10] = t[55];
            p[31] = t[56];
            p[52] = t[57];
            p[9] = t[58];
            p[30] = t[59];
            p[51] = t[60];
            p[8] = t[61];
            p[29] = t[62];
            p[50] = t[63];
            // Linear layer
            l = p ^ rotl64(p, 5) ^ rotl64(p, 13);
            x = l;
        end
    end
    assign out = x;
endmodule
