"""6-stage ornot cascade, schedule D. Adder-latency wave-1 probe (generated by gen_wave1.py)."""
import numpy as np
M64 = np.uint64(0xFFFFFFFFFFFFFFFF)
M32 = np.uint64(0xFFFFFFFF)
RC = np.array([0x9e3779b97f4a7c15, 0x3c6ef372fe94f82a, 0xdaa66d2c7ddf743f, 0x78dde6e5fd29f054, 0x2545f4914f6cdd1d, 0x9e3779b9a1e7c2fa, 0x3c6ef372eca0ae52, 0xdaa66d2cd6129b3e, 0x78dde6e5a883a5fe, 0x2545f4914063d212, 0x9e3779b98fba8ce5, 0x3c6ef372fe6bf8d5], dtype=np.uint64)
def _rotl(x, r):
    r %= 64
    return ((x << np.uint64(r)) | (x >> np.uint64(64 - r))) & M64 if r else x
def _rotl32(x, r):
    r %= 32
    return ((x << np.uint64(r)) | (x >> np.uint64(32 - r))) & M32 if r else x
def _nibchi(x):
    # per-nibble n ^= ((n rol 1) & (n rol 2)) within 4-bit nibbles
    r1 = (((x << np.uint64(1)) & np.uint64(0xEEEEEEEEEEEEEEEE)) |
          ((x >> np.uint64(3)) & np.uint64(0x1111111111111111)))
    r2 = (((x << np.uint64(2)) & np.uint64(0xCCCCCCCCCCCCCCCC)) |
          ((x >> np.uint64(2)) & np.uint64(0x3333333333333333)))
    return (x ^ (r1 & r2)) & M64
def _nibchi_or(x):
    # per-nibble n ^= ((n rol 1) | (n rol 2)) within 4-bit nibbles (OR variant)
    r1 = (((x << np.uint64(1)) & np.uint64(0xEEEEEEEEEEEEEEEE)) |
          ((x >> np.uint64(3)) & np.uint64(0x1111111111111111)))
    r2 = (((x << np.uint64(2)) & np.uint64(0xCCCCCCCCCCCCCCCC)) |
          ((x >> np.uint64(2)) & np.uint64(0x3333333333333333)))
    return (x ^ (r1 | r2)) & M64
STAGES = [(2, 11, 23), (13, 31, 7), (5, 19, 43), (29, 47, 11), (7, 17, 37), (41, 53, 23)]
def mix_np(V, K):
    x = np.asarray(V, dtype=np.uint64); k = np.asarray(K, dtype=np.uint64)
    x = (x ^ k) & M64
    for i,(a,b,c) in enumerate(STAGES):
        t = (x ^ ((_rotl(x,a) ^ M64) | _rotl(x,b)) ^ _rotl(x,c)) & M64
        x = t
    x = (x ^ _rotl(k, 13)) & M64
    return x & M64
def mix(v, k):
    return int(mix_np(np.uint64(v), np.uint64(k)))
