// as6_200_106: and6 sched search as6_200_106 z=5.4 (generated by gen_waveP.py)
module as6_200_106(
    input [63:0] val,
    input [63:0] key,
    output [63:0] out
);
    function [3:0] sbox4(input [3:0] v);
        case (v)
            4'h0: sbox4 = 4'hC;
            4'h1: sbox4 = 4'h6;
            4'h2: sbox4 = 4'h9;
            4'h3: sbox4 = 4'h0;
            4'h4: sbox4 = 4'h1;
            4'h5: sbox4 = 4'hA;
            4'h6: sbox4 = 4'h7;
            4'h7: sbox4 = 4'hB;
            4'h8: sbox4 = 4'h3;
            4'h9: sbox4 = 4'hE;
            4'hA: sbox4 = 4'hF;
            4'hB: sbox4 = 4'h8;
            4'hC: sbox4 = 4'h4;
            4'hD: sbox4 = 4'hD;
            4'hE: sbox4 = 4'h5;
            4'hF: sbox4 = 4'h2;
        endcase
    endfunction
    wire [63:0] x0 = val ^ key;
    wire [63:0] x1 = x0 ^ ({x0[39:0], x0[63:40]} & {x0[6:0], x0[63:7]}) ^ {x0[58:0], x0[63:59]};
    wire [63:0] x2 = x1 ^ ({x1[52:0], x1[63:53]} & {x1[18:0], x1[63:19]}) ^ {x1[32:0], x1[63:33]};
    wire [63:0] x3 = x2 ^ ({x2[55:0], x2[63:56]} & {x2[13:0], x2[63:14]}) ^ {x2[59:0], x2[63:60]};
    wire [63:0] x4 = x3 ^ ({x3[31:0], x3[63:32]} & {x3[40:0], x3[63:41]}) ^ {x3[51:0], x3[63:52]};
    wire [63:0] x5 = x4 ^ ({x4[32:0], x4[63:33]} & {x4[34:0], x4[63:35]}) ^ {x4[57:0], x4[63:58]};
    wire [63:0] x6 = x5 ^ ({x5[2:0], x5[63:3]} & {x5[43:0], x5[63:44]}) ^ {x5[25:0], x5[63:26]};
    wire [63:0] kr = {key[50:0], key[63:51]};
    assign out = x6 ^ kr;
endmodule
