/* Bit-exact C model for dd8_r3_RMR_vlin1_nw (generated by mk_c_impl.py).
 * Construction: 3r SPN, rk_r = rotl64(k, 13u * (unsigned)(r + 1)) ^ RC[r] */
#include <stdint.h>

static const uint8_t SBOX_R0[16] = {0, 1, 2, 3, 4, 6, 8, 11, 13, 9, 7, 15, 12, 10, 5, 14};
static const uint8_t SBOX_R1[16] = {12, 10, 13, 3, 14, 11, 15, 7, 8, 9, 1, 5, 0, 2, 4, 6};
static const uint8_t SBOX_R2[16] = {0, 1, 2, 3, 4, 6, 8, 11, 13, 9, 7, 15, 12, 10, 5, 14};

static const uint8_t PBOX[64] = {1, 20, 39, 58, 13, 32, 51, 6, 25, 44, 63, 18, 37, 56, 11, 30, 49, 4, 23, 42, 61, 16, 35, 54, 9, 28, 47, 2, 21, 40, 59, 14, 33, 52, 7, 26, 45, 0, 19, 38, 57, 12, 31, 50, 5, 24, 43, 62, 17, 36, 55, 10, 29, 48, 3, 22, 41, 60, 15, 34, 53, 8, 27, 46};

static const uint64_t RC[3] = {0x9E3779B97F4A7C15ULL, 0x3C6EF372FE94F82AULL, 0xDAA66D2C7DDF743FULL};

static uint64_t rotl64(uint64_t x, unsigned r) {
    r &= 63;
    return r ? (x << r) | (x >> (64 - r)) : x;
}

uint64_t mix_hash(uint64_t v, uint64_t k) {
    uint64_t x = v;
    for (int r = 0; r < 3; r++) {
        uint64_t rk = (rotl64(k, 13u * (unsigned)(r + 1))) ^ RC[r];
        uint64_t t = x ^ rk;
        /* S-box (per-round table) */
        uint64_t y = 0;
        for (int n = 0; n < 16; n++) {
            uint8_t nib;
            switch (r) {
                case 0: nib = SBOX_R0[(t >> (4*n)) & 0xF]; break;
                case 1: nib = SBOX_R1[(t >> (4*n)) & 0xF]; break;
                case 2: nib = SBOX_R2[(t >> (4*n)) & 0xF]; break;
                default: nib = 0; break;
            }
            y |= (uint64_t)nib << (4*n);
        }
        /* P-box */
        uint64_t z = 0;
        for (int i = 0; i < 64; i++)
            z |= ((y >> i) & 1ULL) << PBOX[i];
        /* LIN: per-round rotation pair */
        switch (r) {
            case 0: x = z ^ rotl64(z, 5) ^ rotl64(z, 13); break;
            case 1: x = z ^ rotl64(z, 8) ^ rotl64(z, 15); break;
            case 2: x = z ^ rotl64(z, 3) ^ rotl64(z, 11); break;
            default: x = z; break;
        }
    }
    return x;
}
