// as6_200_67: and6 sched search as6_200_67 z=8.1 (generated by gen_waveP.py)
module as6_200_67(
    input [63:0] val,
    input [63:0] key,
    output [63:0] out
);
    function [3:0] sbox4(input [3:0] v);
        case (v)
            4'h0: sbox4 = 4'hC;
            4'h1: sbox4 = 4'h6;
            4'h2: sbox4 = 4'h9;
            4'h3: sbox4 = 4'h0;
            4'h4: sbox4 = 4'h1;
            4'h5: sbox4 = 4'hA;
            4'h6: sbox4 = 4'h7;
            4'h7: sbox4 = 4'hB;
            4'h8: sbox4 = 4'h3;
            4'h9: sbox4 = 4'hE;
            4'hA: sbox4 = 4'hF;
            4'hB: sbox4 = 4'h8;
            4'hC: sbox4 = 4'h4;
            4'hD: sbox4 = 4'hD;
            4'hE: sbox4 = 4'h5;
            4'hF: sbox4 = 4'h2;
        endcase
    endfunction
    wire [63:0] x0 = val ^ key;
    wire [63:0] x1 = x0 ^ ({x0[29:0], x0[63:30]} & {x0[51:0], x0[63:52]}) ^ {x0[48:0], x0[63:49]};
    wire [63:0] x2 = x1 ^ ({x1[7:0], x1[63:8]} & {x1[57:0], x1[63:58]}) ^ {x1[3:0], x1[63:4]};
    wire [63:0] x3 = x2 ^ ({x2[21:0], x2[63:22]} & {x2[40:0], x2[63:41]}) ^ {x2[61:0], x2[63:62]};
    wire [63:0] x4 = x3 ^ ({x3[18:0], x3[63:19]} & {x3[51:0], x3[63:52]}) ^ {x3[11:0], x3[63:12]};
    wire [63:0] x5 = x4 ^ ({x4[32:0], x4[63:33]} & {x4[62:0], x4[63:63]}) ^ {x4[45:0], x4[63:46]};
    wire [63:0] x6 = x5 ^ ({x5[25:0], x5[63:26]} & {x5[24:0], x5[63:25]}) ^ {x5[7:0], x5[63:8]};
    wire [63:0] kr = {key[50:0], key[63:51]};
    assign out = x6 ^ kr;
endmodule
