// fz13_het5a: generated by gen_fused13.py
module fz13_het5a(
    input  wire [63:0] v,
    input  wire [63:0] k,
    output wire [63:0] out
);
    function [63:0] rotl;
        input [63:0] x;
        input integer r;
        begin
            r = r % 64;
            rotl = r ? ((x << r) | (x >> (64 - r))) : x;
        end
    endfunction
    wire [63:0] x0 = v ^ k;
    wire [63:0] r0_1 = rotl(x0, 1);
    wire [63:0] r0_2 = rotl(x0, 2);
    wire [63:0] r0_13 = rotl(x0, 13);
    wire [63:0] x1 = (x0 ^ (r0_1 & r0_2) ^ r0_13);
    wire [63:0] r1_5 = rotl(x1, 5);
    wire [63:0] r1_7 = rotl(x1, 7);
    wire [63:0] r1_19 = rotl(x1, 19);
    wire [63:0] x2 = (x1 ^ (r1_7 & r1_19) ^ r1_5);
    wire [63:0] r2_3 = rotl(x2, 3);
    wire [63:0] r2_11 = rotl(x2, 11);
    wire [63:0] r2_29 = rotl(x2, 29);
    wire [63:0] x3 = (x2 ^ ((r2_3 & r2_11) | (r2_3 & r2_29) | (r2_11 & r2_29)));
    wire [63:0] r3_7 = rotl(x3, 7);
    wire [63:0] r3_17 = rotl(x3, 17);
    wire [63:0] r3_31 = rotl(x3, 31);
    wire [63:0] x4 = (x3 ^ (r3_17 & r3_31) ^ r3_7);
    wire [63:0] r4_11 = rotl(x4, 11);
    wire [63:0] r4_23 = rotl(x4, 23);
    wire [63:0] r4_37 = rotl(x4, 37);
    wire [63:0] x5 = (x4 ^ (r4_11 & r4_23) ^ r4_37);
    wire [63:0] k13 = rotl(k, 13);
    assign out = x5 ^ k13;
endmodule
