// hyb12_asb4a: 4xAND (triplets 1-4) + rasC2_0 S-box layer + L(5,13): FRONTIER CHALLENGER (generated by hybrid/codesign/gen_batch12.py)
module hyb12_asb4a(
    input [63:0] val,
    input [63:0] key,
    output [63:0] out
);
    function [3:0] sb(input [3:0] z);
        begin
            case (z)
                4'h0: sb = 4'h0;
                4'h1: sb = 4'h1;
                4'h2: sb = 4'h2;
                4'h3: sb = 4'h3;
                4'h4: sb = 4'h4;
                4'h5: sb = 4'h6;
                4'h6: sb = 4'h8;
                4'h7: sb = 4'hb;
                4'h8: sb = 4'hd;
                4'h9: sb = 4'h9;
                4'ha: sb = 4'h7;
                4'hb: sb = 4'hf;
                4'hc: sb = 4'hc;
                4'hd: sb = 4'ha;
                4'he: sb = 4'h5;
                4'hf: sb = 4'he;
                default: sb = 4'h0;
            endcase
        end
    endfunction
    wire [63:0] x0 = val ^ key;
    wire [63:0] s0a = {x0[62:0], x0[63:63]};
    wire [63:0] s0b = {x0[61:0], x0[63:62]};
    wire [63:0] s0c = {x0[50:0], x0[63:51]};
    wire [63:0] t0 = x0 ^ (s0a & s0b) ^ s0c;
    wire [63:0] s1a = {t0[56:0], t0[63:57]};
    wire [63:0] s1b = {t0[44:0], t0[63:45]};
    wire [63:0] s1c = {t0[58:0], t0[63:59]};
    wire [63:0] t1 = t0 ^ (s1a & s1b) ^ s1c;
    wire [63:0] s2a = {t1[60:0], t1[63:61]};
    wire [63:0] s2b = {t1[52:0], t1[63:53]};
    wire [63:0] s2c = {t1[34:0], t1[63:35]};
    wire [63:0] t2 = t1 ^ (s2a & s2b) ^ s2c;
    wire [63:0] s3a = {t2[46:0], t2[63:47]};
    wire [63:0] s3b = {t2[32:0], t2[63:33]};
    wire [63:0] s3c = {t2[56:0], t2[63:57]};
    wire [63:0] t3 = t2 ^ (s3a & s3b) ^ s3c;
    wire [63:0] sbx = {sb(t3[63:60]), sb(t3[59:56]), sb(t3[55:52]), sb(t3[51:48]), sb(t3[47:44]), sb(t3[43:40]), sb(t3[39:36]), sb(t3[35:32]), sb(t3[31:28]), sb(t3[27:24]), sb(t3[23:20]), sb(t3[19:16]), sb(t3[15:12]), sb(t3[11:8]), sb(t3[7:4]), sb(t3[3:0])};
    wire [63:0] lf = sbx ^ {sbx[58:0], sbx[63:59]} ^ {sbx[50:0], sbx[63:51]};
    wire [63:0] kr = {key[50:0], key[63:51]};
    assign out = lf ^ kr;
endmodule
