// al_andor9b: 6-stage alternating AND/OR cascade (generated by Track 3 wave-9)
#include <stdint.h>

static inline uint64_t rotl64(uint64_t x, unsigned r) {
    r &= 63;
    return r ? (x << r) | (x >> (64 - r)) : x;
}

uint64_t mix_hash(uint64_t v, uint64_t k) {
    uint64_t x = v ^ k;
    x = x ^ (rotl64(x, 2) | rotl64(x, 5)) ^ rotl64(x, 11);  // stage 0 OR
    x = x ^ (rotl64(x, 3) & rotl64(x, 13)) ^ rotl64(x, 19);  // stage 1 AND
    x = x ^ (rotl64(x, 7) | rotl64(x, 21)) ^ rotl64(x, 5);  // stage 2 OR
    x = x ^ (rotl64(x, 11) | rotl64(x, 25)) ^ rotl64(x, 13);  // stage 3 OR
    x = x ^ (rotl64(x, 13) & rotl64(x, 26)) ^ rotl64(x, 7);  // stage 4 AND
    x = x ^ (rotl64(x, 19) | rotl64(x, 43)) ^ rotl64(x, 17);  // stage 5 OR
    x = x ^ rotl64(k, 13);
    return x;
}
