// as6_200_68: and6 sched search as6_200_68 z=7.6 (generated by gen_waveP.py)
module as6_200_68(
    input [63:0] val,
    input [63:0] key,
    output [63:0] out
);
    function [3:0] sbox4(input [3:0] v);
        case (v)
            4'h0: sbox4 = 4'hC;
            4'h1: sbox4 = 4'h6;
            4'h2: sbox4 = 4'h9;
            4'h3: sbox4 = 4'h0;
            4'h4: sbox4 = 4'h1;
            4'h5: sbox4 = 4'hA;
            4'h6: sbox4 = 4'h7;
            4'h7: sbox4 = 4'hB;
            4'h8: sbox4 = 4'h3;
            4'h9: sbox4 = 4'hE;
            4'hA: sbox4 = 4'hF;
            4'hB: sbox4 = 4'h8;
            4'hC: sbox4 = 4'h4;
            4'hD: sbox4 = 4'hD;
            4'hE: sbox4 = 4'h5;
            4'hF: sbox4 = 4'h2;
        endcase
    endfunction
    wire [63:0] x0 = val ^ key;
    wire [63:0] x1 = x0 ^ ({x0[10:0], x0[63:11]} & {x0[51:0], x0[63:52]}) ^ {x0[16:0], x0[63:17]};
    wire [63:0] x2 = x1 ^ ({x1[51:0], x1[63:52]} & {x1[18:0], x1[63:19]}) ^ {x1[27:0], x1[63:28]};
    wire [63:0] x3 = x2 ^ ({x2[58:0], x2[63:59]} & {x2[45:0], x2[63:46]}) ^ {x2[13:0], x2[63:14]};
    wire [63:0] x4 = x3 ^ ({x3[30:0], x3[63:31]} & {x3[59:0], x3[63:60]}) ^ {x3[15:0], x3[63:16]};
    wire [63:0] x5 = x4 ^ ({x4[18:0], x4[63:19]} & {x4[35:0], x4[63:36]}) ^ {x4[50:0], x4[63:51]};
    wire [63:0] x6 = x5 ^ ({x5[35:0], x5[63:36]} & {x5[45:0], x5[63:46]}) ^ {x5[8:0], x5[63:9]};
    wire [63:0] kr = {key[50:0], key[63:51]};
    assign out = x6 ^ kr;
endmodule
