// hyb11_and6_finalPL: 6-stage al_and6a triplets + final P(37,1)+L(5,13) (control: final layer on frontier design) (generated by hybrid/codesign/gen_batch11.py)
#include <stdint.h>
static inline uint64_t rotl64(uint64_t x, int r) {
    r &= 63;
    return r ? (x << r) | (x >> (64 - r)) : x;
}
static inline uint64_t pbox64(uint64_t x) { /* P(i)=(37*i+1)%64 */
    uint64_t y = 0;
    y |= ((x >> 0) & 1ULL) << 1;
    y |= ((x >> 1) & 1ULL) << 38;
    y |= ((x >> 2) & 1ULL) << 11;
    y |= ((x >> 3) & 1ULL) << 48;
    y |= ((x >> 4) & 1ULL) << 21;
    y |= ((x >> 5) & 1ULL) << 58;
    y |= ((x >> 6) & 1ULL) << 31;
    y |= ((x >> 7) & 1ULL) << 4;
    y |= ((x >> 8) & 1ULL) << 41;
    y |= ((x >> 9) & 1ULL) << 14;
    y |= ((x >> 10) & 1ULL) << 51;
    y |= ((x >> 11) & 1ULL) << 24;
    y |= ((x >> 12) & 1ULL) << 61;
    y |= ((x >> 13) & 1ULL) << 34;
    y |= ((x >> 14) & 1ULL) << 7;
    y |= ((x >> 15) & 1ULL) << 44;
    y |= ((x >> 16) & 1ULL) << 17;
    y |= ((x >> 17) & 1ULL) << 54;
    y |= ((x >> 18) & 1ULL) << 27;
    y |= ((x >> 19) & 1ULL) << 0;
    y |= ((x >> 20) & 1ULL) << 37;
    y |= ((x >> 21) & 1ULL) << 10;
    y |= ((x >> 22) & 1ULL) << 47;
    y |= ((x >> 23) & 1ULL) << 20;
    y |= ((x >> 24) & 1ULL) << 57;
    y |= ((x >> 25) & 1ULL) << 30;
    y |= ((x >> 26) & 1ULL) << 3;
    y |= ((x >> 27) & 1ULL) << 40;
    y |= ((x >> 28) & 1ULL) << 13;
    y |= ((x >> 29) & 1ULL) << 50;
    y |= ((x >> 30) & 1ULL) << 23;
    y |= ((x >> 31) & 1ULL) << 60;
    y |= ((x >> 32) & 1ULL) << 33;
    y |= ((x >> 33) & 1ULL) << 6;
    y |= ((x >> 34) & 1ULL) << 43;
    y |= ((x >> 35) & 1ULL) << 16;
    y |= ((x >> 36) & 1ULL) << 53;
    y |= ((x >> 37) & 1ULL) << 26;
    y |= ((x >> 38) & 1ULL) << 63;
    y |= ((x >> 39) & 1ULL) << 36;
    y |= ((x >> 40) & 1ULL) << 9;
    y |= ((x >> 41) & 1ULL) << 46;
    y |= ((x >> 42) & 1ULL) << 19;
    y |= ((x >> 43) & 1ULL) << 56;
    y |= ((x >> 44) & 1ULL) << 29;
    y |= ((x >> 45) & 1ULL) << 2;
    y |= ((x >> 46) & 1ULL) << 39;
    y |= ((x >> 47) & 1ULL) << 12;
    y |= ((x >> 48) & 1ULL) << 49;
    y |= ((x >> 49) & 1ULL) << 22;
    y |= ((x >> 50) & 1ULL) << 59;
    y |= ((x >> 51) & 1ULL) << 32;
    y |= ((x >> 52) & 1ULL) << 5;
    y |= ((x >> 53) & 1ULL) << 42;
    y |= ((x >> 54) & 1ULL) << 15;
    y |= ((x >> 55) & 1ULL) << 52;
    y |= ((x >> 56) & 1ULL) << 25;
    y |= ((x >> 57) & 1ULL) << 62;
    y |= ((x >> 58) & 1ULL) << 35;
    y |= ((x >> 59) & 1ULL) << 8;
    y |= ((x >> 60) & 1ULL) << 45;
    y |= ((x >> 61) & 1ULL) << 18;
    y |= ((x >> 62) & 1ULL) << 55;
    y |= ((x >> 63) & 1ULL) << 28;
    return y;
}
static inline uint64_t lin513(uint64_t x) {
    return x ^ rotl64(x, 5) ^ rotl64(x, 13);
}
uint64_t mix_hash(uint64_t val, uint64_t key) {
    uint64_t x = val ^ key;
    { /* AND stage 0: (1,2,13) */
        uint64_t ra = rotl64(x, 1), rb = rotl64(x, 2), rc = rotl64(x, 13);
        x ^= (ra & rb) ^ rc;
    }
    { /* AND stage 1: (7,19,5) */
        uint64_t ra = rotl64(x, 7), rb = rotl64(x, 19), rc = rotl64(x, 5);
        x ^= (ra & rb) ^ rc;
    }
    { /* AND stage 2: (3,11,29) */
        uint64_t ra = rotl64(x, 3), rb = rotl64(x, 11), rc = rotl64(x, 29);
        x ^= (ra & rb) ^ rc;
    }
    { /* AND stage 3: (17,31,7) */
        uint64_t ra = rotl64(x, 17), rb = rotl64(x, 31), rc = rotl64(x, 7);
        x ^= (ra & rb) ^ rc;
    }
    { /* AND stage 4: (11,23,37) */
        uint64_t ra = rotl64(x, 11), rb = rotl64(x, 23), rc = rotl64(x, 37);
        x ^= (ra & rb) ^ rc;
    }
    { /* AND stage 5: (19,41,23) */
        uint64_t ra = rotl64(x, 19), rb = rotl64(x, 41), rc = rotl64(x, 23);
        x ^= (ra & rb) ^ rc;
    }
    x = pbox64(x);
    x = lin513(x);
    x ^= rotl64(key, 13);
    return x;
}
