// hyb11_and6_finalPL: 6-stage al_and6a triplets + final P(37,1)+L(5,13) (control: final layer on frontier design) (generated by hybrid/codesign/gen_batch11.py)
module hyb11_and6_finalPL(
    input [63:0] val,
    input [63:0] key,
    output [63:0] out
);
    wire [63:0] x0 = val ^ key;
    wire [63:0] s0a = {x0[62:0], x0[63:63]};
    wire [63:0] s0b = {x0[61:0], x0[63:62]};
    wire [63:0] s0c = {x0[50:0], x0[63:51]};
    wire [63:0] t0 = x0 ^ (s0a & s0b) ^ s0c;
    wire [63:0] s1a = {t0[56:0], t0[63:57]};
    wire [63:0] s1b = {t0[44:0], t0[63:45]};
    wire [63:0] s1c = {t0[58:0], t0[63:59]};
    wire [63:0] t1 = t0 ^ (s1a & s1b) ^ s1c;
    wire [63:0] s2a = {t1[60:0], t1[63:61]};
    wire [63:0] s2b = {t1[52:0], t1[63:53]};
    wire [63:0] s2c = {t1[34:0], t1[63:35]};
    wire [63:0] t2 = t1 ^ (s2a & s2b) ^ s2c;
    wire [63:0] s3a = {t2[46:0], t2[63:47]};
    wire [63:0] s3b = {t2[32:0], t2[63:33]};
    wire [63:0] s3c = {t2[56:0], t2[63:57]};
    wire [63:0] t3 = t2 ^ (s3a & s3b) ^ s3c;
    wire [63:0] s4a = {t3[52:0], t3[63:53]};
    wire [63:0] s4b = {t3[40:0], t3[63:41]};
    wire [63:0] s4c = {t3[26:0], t3[63:27]};
    wire [63:0] t4 = t3 ^ (s4a & s4b) ^ s4c;
    wire [63:0] s5a = {t4[44:0], t4[63:45]};
    wire [63:0] s5b = {t4[22:0], t4[63:23]};
    wire [63:0] s5c = {t4[40:0], t4[63:41]};
    wire [63:0] t5 = t4 ^ (s5a & s5b) ^ s5c;
    wire [63:0] pf = {t5[38], t5[57], t5[12], t5[31], t5[50], t5[5], t5[24], t5[43], t5[62], t5[17], t5[36], t5[55], t5[10], t5[29], t5[48], t5[3], t5[22], t5[41], t5[60], t5[15], t5[34], t5[53], t5[8], t5[27], t5[46], t5[1], t5[20], t5[39], t5[58], t5[13], t5[32], t5[51], t5[6], t5[25], t5[44], t5[63], t5[18], t5[37], t5[56], t5[11], t5[30], t5[49], t5[4], t5[23], t5[42], t5[61], t5[16], t5[35], t5[54], t5[9], t5[28], t5[47], t5[2], t5[21], t5[40], t5[59], t5[14], t5[33], t5[52], t5[7], t5[26], t5[45], t5[0], t5[19]};
    wire [63:0] lf = pf ^ {pf[58:0], pf[63:59]} ^ {pf[50:0], pf[63:51]};
    wire [63:0] kr = {key[50:0], key[63:51]};
    assign out = lf ^ kr;
endmodule
