// al_ornot6c: 6-stage ornot cascade, schedule C (generated by gen_wave1.py)
module al_ornot6c(
    input [63:0] v,
    input [63:0] k,
    output [63:0] o
);
    wire [63:0] x0 = v ^ k;
    wire [63:0] s0a = {x0[58:0], x0[63:59]};
    wire [63:0] s0b = {x0[50:0], x0[63:51]};
    wire [63:0] s0c = {x0[34:0], x0[63:35]};
    wire [63:0] x1 = x0 ^ ((~s0a) | s0b) ^ s0c;
    wire [63:0] s1a = {x1[56:0], x1[63:57]};
    wire [63:0] s1b = {x1[40:0], x1[63:41]};
    wire [63:0] s1c = {x1[22:0], x1[63:23]};
    wire [63:0] x2 = x1 ^ ((~s1a) | s1b) ^ s1c;
    wire [63:0] s2a = {x2[46:0], x2[63:47]};
    wire [63:0] s2b = {x2[26:0], x2[63:27]};
    wire [63:0] s2c = {x2[52:0], x2[63:53]};
    wire [63:0] x3 = x2 ^ ((~s2a) | s2b) ^ s2c;
    wire [63:0] s3a = {x3[60:0], x3[63:61]};
    wire [63:0] s3b = {x3[44:0], x3[63:45]};
    wire [63:0] s3c = {x3[16:0], x3[63:17]};
    wire [63:0] x4 = x3 ^ ((~s3a) | s3b) ^ s3c;
    wire [63:0] s4a = {x4[40:0], x4[63:41]};
    wire [63:0] s4b = {x4[20:0], x4[63:21]};
    wire [63:0] s4c = {x4[50:0], x4[63:51]};
    wire [63:0] x5 = x4 ^ ((~s4a) | s4b) ^ s4c;
    wire [63:0] s5a = {x5[32:0], x5[63:33]};
    wire [63:0] s5b = {x5[4:0], x5[63:5]};
    wire [63:0] s5c = {x5[56:0], x5[63:57]};
    wire [63:0] x6 = x5 ^ ((~s5a) | s5b) ^ s5c;
    wire [63:0] kr = {k[50:0], k[63:51]};
    assign o = x6 ^ kr;
endmodule
