// as6_200_80: and6 sched search as6_200_80 z=8.2 (generated by gen_waveP.py)
module as6_200_80(
    input [63:0] val,
    input [63:0] key,
    output [63:0] out
);
    function [3:0] sbox4(input [3:0] v);
        case (v)
            4'h0: sbox4 = 4'hC;
            4'h1: sbox4 = 4'h6;
            4'h2: sbox4 = 4'h9;
            4'h3: sbox4 = 4'h0;
            4'h4: sbox4 = 4'h1;
            4'h5: sbox4 = 4'hA;
            4'h6: sbox4 = 4'h7;
            4'h7: sbox4 = 4'hB;
            4'h8: sbox4 = 4'h3;
            4'h9: sbox4 = 4'hE;
            4'hA: sbox4 = 4'hF;
            4'hB: sbox4 = 4'h8;
            4'hC: sbox4 = 4'h4;
            4'hD: sbox4 = 4'hD;
            4'hE: sbox4 = 4'h5;
            4'hF: sbox4 = 4'h2;
        endcase
    endfunction
    wire [63:0] x0 = val ^ key;
    wire [63:0] x1 = x0 ^ ({x0[38:0], x0[63:39]} & {x0[57:0], x0[63:58]}) ^ {x0[35:0], x0[63:36]};
    wire [63:0] x2 = x1 ^ ({x1[14:0], x1[63:15]} & {x1[30:0], x1[63:31]}) ^ {x1[12:0], x1[63:13]};
    wire [63:0] x3 = x2 ^ ({x2[16:0], x2[63:17]} & {x2[54:0], x2[63:55]}) ^ {x2[4:0], x2[63:5]};
    wire [63:0] x4 = x3 ^ ({x3[22:0], x3[63:23]} & {x3[60:0], x3[63:61]}) ^ {x3[40:0], x3[63:41]};
    wire [63:0] x5 = x4 ^ ({x4[0:0], x4[63:1]} & {x4[39:0], x4[63:40]}) ^ {x4[16:0], x4[63:17]};
    wire [63:0] x6 = x5 ^ ({x5[2:0], x5[63:3]} & {x5[20:0], x5[63:21]}) ^ {x5[21:0], x5[63:22]};
    wire [63:0] kr = {key[50:0], key[63:51]};
    assign out = x6 ^ kr;
endmodule
