// as6_200_38: and6 sched search as6_200_38 z=7.8 (generated by gen_waveP.py)
module as6_200_38(
    input [63:0] val,
    input [63:0] key,
    output [63:0] out
);
    function [3:0] sbox4(input [3:0] v);
        case (v)
            4'h0: sbox4 = 4'hC;
            4'h1: sbox4 = 4'h6;
            4'h2: sbox4 = 4'h9;
            4'h3: sbox4 = 4'h0;
            4'h4: sbox4 = 4'h1;
            4'h5: sbox4 = 4'hA;
            4'h6: sbox4 = 4'h7;
            4'h7: sbox4 = 4'hB;
            4'h8: sbox4 = 4'h3;
            4'h9: sbox4 = 4'hE;
            4'hA: sbox4 = 4'hF;
            4'hB: sbox4 = 4'h8;
            4'hC: sbox4 = 4'h4;
            4'hD: sbox4 = 4'hD;
            4'hE: sbox4 = 4'h5;
            4'hF: sbox4 = 4'h2;
        endcase
    endfunction
    wire [63:0] x0 = val ^ key;
    wire [63:0] x1 = x0 ^ ({x0[24:0], x0[63:25]} & {x0[38:0], x0[63:39]}) ^ {x0[20:0], x0[63:21]};
    wire [63:0] x2 = x1 ^ ({x1[37:0], x1[63:38]} & {x1[10:0], x1[63:11]}) ^ {x1[29:0], x1[63:30]};
    wire [63:0] x3 = x2 ^ ({x2[30:0], x2[63:31]} & {x2[55:0], x2[63:56]}) ^ {x2[21:0], x2[63:22]};
    wire [63:0] x4 = x3 ^ ({x3[10:0], x3[63:11]} & {x3[21:0], x3[63:22]}) ^ {x3[16:0], x3[63:17]};
    wire [63:0] x5 = x4 ^ ({x4[62:0], x4[63:63]} & {x4[35:0], x4[63:36]}) ^ {x4[2:0], x4[63:3]};
    wire [63:0] x6 = x5 ^ ({x5[25:0], x5[63:26]} & {x5[41:0], x5[63:42]}) ^ {x5[33:0], x5[63:34]};
    wire [63:0] kr = {key[50:0], key[63:51]};
    assign out = x6 ^ kr;
endmodule
