"""and6 sched search as6_200_15 z=5.1. Adder-latency wave-1 probe (generated by gen_wave1.py)."""
import numpy as np
M64 = np.uint64(0xFFFFFFFFFFFFFFFF)
M32 = np.uint64(0xFFFFFFFF)
RC = np.array([0x9e3779b97f4a7c15, 0x3c6ef372fe94f82a, 0xdaa66d2c7ddf743f, 0x78dde6e5fd29f054, 0x2545f4914f6cdd1d, 0x9e3779b9a1e7c2fa, 0x3c6ef372eca0ae52, 0xdaa66d2cd6129b3e, 0x78dde6e5a883a5fe, 0x2545f4914063d212, 0x9e3779b98fba8ce5, 0x3c6ef372fe6bf8d5], dtype=np.uint64)
def _rotl(x, r):
    r %= 64
    return ((x << np.uint64(r)) | (x >> np.uint64(64 - r))) & M64 if r else x
def _rotl32(x, r):
    r %= 32
    return ((x << np.uint64(r)) | (x >> np.uint64(32 - r))) & M32 if r else x
def _nibchi(x):
    # per-nibble n ^= ((n rol 1) & (n rol 2)) within 4-bit nibbles
    r1 = (((x << np.uint64(1)) & np.uint64(0xEEEEEEEEEEEEEEEE)) |
          ((x >> np.uint64(3)) & np.uint64(0x1111111111111111)))
    r2 = (((x << np.uint64(2)) & np.uint64(0xCCCCCCCCCCCCCCCC)) |
          ((x >> np.uint64(2)) & np.uint64(0x3333333333333333)))
    return (x ^ (r1 & r2)) & M64
def _nibchi_or(x):
    # per-nibble n ^= ((n rol 1) | (n rol 2)) within 4-bit nibbles (OR variant)
    r1 = (((x << np.uint64(1)) & np.uint64(0xEEEEEEEEEEEEEEEE)) |
          ((x >> np.uint64(3)) & np.uint64(0x1111111111111111)))
    r2 = (((x << np.uint64(2)) & np.uint64(0xCCCCCCCCCCCCCCCC)) |
          ((x >> np.uint64(2)) & np.uint64(0x3333333333333333)))
    return (x ^ (r1 | r2)) & M64
SBOX = [12, 6, 9, 0, 1, 10, 7, 11, 3, 14, 15, 8, 4, 13, 5, 2]
SBOX_ARR = np.array(SBOX, dtype=np.uint64)
STAGES = [('and', 46, 40, 18), ('and', 13, 41, 26), ('and', 42, 23, 25), ('and', 62, 27, 57), ('and', 21, 27, 39), ('and', 15, 55, 22)]
def _sbox64(x):
    y = np.zeros_like(x)
    for i in range(16):
        nib = (x >> np.uint64(4*i)) & np.uint64(0xF)
        y |= SBOX_ARR[nib] << np.uint64(4*i)
    return y & M64
def mix_np(V, K):
    x = np.asarray(V, dtype=np.uint64); k = np.asarray(K, dtype=np.uint64)
    x = (x ^ k) & M64
    for st in STAGES:
        t = st[0]
        if t == 'and':
            x = (x ^ (_rotl(x, st[1]) & _rotl(x, st[2])) ^ _rotl(x, st[3])) & M64
        elif t == 't3':
            x = (x ^ (_rotl(x, st[1]) & _rotl(x, st[2])) ^ _rotl(x, st[3]) ^ _rotl(x, st[4])) & M64
        elif t == 'dual':
            x = (x ^ (_rotl(x, st[1]) & _rotl(x, st[2])) ^ (_rotl(x, st[3]) & _rotl(x, st[4])) ^ _rotl(x, st[5])) & M64
        elif t == 'sbox':
            x = _sbox64(x)
        elif t == 'sboxL':
            x = _sbox64(x)
            x = (x ^ _rotl(x, st[1]) ^ _rotl(x, st[2])) & M64
        else:
            raise ValueError(st)
    x = (x ^ _rotl(k, 13)) & M64
    return x & M64
def mix(v, k):
    return int(mix_np(np.uint64(v), np.uint64(k)))
