// as6_200_15: and6 sched search as6_200_15 z=5.1 (generated by gen_waveP.py)
module as6_200_15(
    input [63:0] val,
    input [63:0] key,
    output [63:0] out
);
    function [3:0] sbox4(input [3:0] v);
        case (v)
            4'h0: sbox4 = 4'hC;
            4'h1: sbox4 = 4'h6;
            4'h2: sbox4 = 4'h9;
            4'h3: sbox4 = 4'h0;
            4'h4: sbox4 = 4'h1;
            4'h5: sbox4 = 4'hA;
            4'h6: sbox4 = 4'h7;
            4'h7: sbox4 = 4'hB;
            4'h8: sbox4 = 4'h3;
            4'h9: sbox4 = 4'hE;
            4'hA: sbox4 = 4'hF;
            4'hB: sbox4 = 4'h8;
            4'hC: sbox4 = 4'h4;
            4'hD: sbox4 = 4'hD;
            4'hE: sbox4 = 4'h5;
            4'hF: sbox4 = 4'h2;
        endcase
    endfunction
    wire [63:0] x0 = val ^ key;
    wire [63:0] x1 = x0 ^ ({x0[17:0], x0[63:18]} & {x0[23:0], x0[63:24]}) ^ {x0[45:0], x0[63:46]};
    wire [63:0] x2 = x1 ^ ({x1[50:0], x1[63:51]} & {x1[22:0], x1[63:23]}) ^ {x1[37:0], x1[63:38]};
    wire [63:0] x3 = x2 ^ ({x2[21:0], x2[63:22]} & {x2[40:0], x2[63:41]}) ^ {x2[38:0], x2[63:39]};
    wire [63:0] x4 = x3 ^ ({x3[1:0], x3[63:2]} & {x3[36:0], x3[63:37]}) ^ {x3[6:0], x3[63:7]};
    wire [63:0] x5 = x4 ^ ({x4[42:0], x4[63:43]} & {x4[36:0], x4[63:37]}) ^ {x4[24:0], x4[63:25]};
    wire [63:0] x6 = x5 ^ ({x5[48:0], x5[63:49]} & {x5[8:0], x5[63:9]}) ^ {x5[41:0], x5[63:42]};
    wire [63:0] kr = {key[50:0], key[63:51]};
    assign out = x6 ^ kr;
endmodule
