// hyb18_dual_b: 5-stage [and,and,and,t3,dual]: dual-last-stage, proxy z=7.9, est 19.55u (generated by hybrid/batch18/gen_batch18.py)
#include <stdint.h>
static inline uint64_t rotl64(uint64_t x, int r) {
    r &= 63;
    return r ? (x << r) | (x >> (64 - r)) : x;
}
uint64_t mix_hash(uint64_t val, uint64_t key) {
    uint64_t x = val ^ key;
    { /* AND stage 0 */
        uint64_t ra=rotl64(x,5),rb=rotl64(x,4),rc=rotl64(x,38);
        x ^= (ra & rb) ^ rc;
    }
    { /* AND stage 1 */
        uint64_t ra=rotl64(x,63),rb=rotl64(x,14),rc=rotl64(x,12);
        x ^= (ra & rb) ^ rc;
    }
    { /* AND stage 2 */
        uint64_t ra=rotl64(x,17),rb=rotl64(x,49),rc=rotl64(x,58);
        x ^= (ra & rb) ^ rc;
    }
    { /* T3 stage 3 */
        uint64_t ra=rotl64(x,12),rb=rotl64(x,62),rc=rotl64(x,52),re=rotl64(x,4);
        x ^= (ra & rb) ^ rc ^ re;
    }
    { /* DUAL stage 4 */
        uint64_t ra=rotl64(x,12),rb=rotl64(x,47),rc=rotl64(x,45),rd=rotl64(x,7),re=rotl64(x,50);
        x ^= (ra & rb) ^ (rc & rd) ^ re;
    }
    return x ^ rotl64(key, 13);
}
