"""hyb18_dual_b: 5-stage [and,and,and,t3,dual]: dual-last-stage, proxy z=7.9, est 19.55u (generated by hybrid/batch18/gen_batch18.py)"""
import numpy as np
M64=np.uint64(0xFFFFFFFFFFFFFFFF)
def rotl(x,r):
    r%=64
    return ((x<<np.uint64(r))|(x>>np.uint64(64-r)))&M64 if r else x
STAGES=[['and', 5, 4, 38], ['and', 63, 14, 12], ['and', 17, 49, 58], ['t3', 12, 62, 52, 4], ['dual', 12, 47, 45, 7, 50]]
def apply_stage(x,st):
    t=st[0]
    if t=='and':
        _,a,b,c=st; return (x^(rotl(x,a)&rotl(x,b))^rotl(x,c))&M64
    if t=='t3':
        _,a,b,c,e=st; return (x^(rotl(x,a)&rotl(x,b))^rotl(x,c)^rotl(x,e))&M64
    if t=='dual':
        _,a,b,c,dd,e=st; return (x^(rotl(x,a)&rotl(x,b))^(rotl(x,c)&rotl(x,dd))^rotl(x,e))&M64
    raise ValueError(st)
def mix_hash(val,key):
    x=np.uint64(val)^np.uint64(key)
    for st in STAGES:
        x=apply_stage(x,st)
    return int((x^rotl(np.uint64(key),13))&M64)
