// hyb18_dual_b: 5-stage [and,and,and,t3,dual]: dual-last-stage, proxy z=7.9, est 19.55u (generated by hybrid/batch18/gen_batch18.py)
module mix_hash(input [63:0] val, input [63:0] key, output [63:0] out);
    wire [63:0] x0 = val ^ key;
    wire [63:0] x1_ra = {x0[58:0], x0[63:59]};
    wire [63:0] x1_rb = {x0[59:0], x0[63:60]};
    wire [63:0] x1_rc = {x0[25:0], x0[63:26]};
    wire [63:0] x1 = x0 ^ (x1_ra & x1_rb) ^ x1_rc;
    wire [63:0] x2_ra = {x1[0:0], x1[63:1]};
    wire [63:0] x2_rb = {x1[49:0], x1[63:50]};
    wire [63:0] x2_rc = {x1[51:0], x1[63:52]};
    wire [63:0] x2 = x1 ^ (x2_ra & x2_rb) ^ x2_rc;
    wire [63:0] x3_ra = {x2[46:0], x2[63:47]};
    wire [63:0] x3_rb = {x2[14:0], x2[63:15]};
    wire [63:0] x3_rc = {x2[5:0], x2[63:6]};
    wire [63:0] x3 = x2 ^ (x3_ra & x3_rb) ^ x3_rc;
    wire [63:0] x4_ra = {x3[51:0], x3[63:52]};
    wire [63:0] x4_rb = {x3[1:0], x3[63:2]};
    wire [63:0] x4_rc = {x3[11:0], x3[63:12]};
    wire [63:0] x4_re = {x3[59:0], x3[63:60]};
    wire [63:0] x4 = x3 ^ (x4_ra & x4_rb) ^ x4_rc ^ x4_re;
    wire [63:0] x5_ra = {x4[51:0], x4[63:52]};
    wire [63:0] x5_rb = {x4[16:0], x4[63:17]};
    wire [63:0] x5_rc = {x4[18:0], x4[63:19]};
    wire [63:0] x5_rd = {x4[56:0], x4[63:57]};
    wire [63:0] x5_re = {x4[13:0], x4[63:14]};
    wire [63:0] x5 = x4 ^ (x5_ra & x5_rb) ^ (x5_rc & x5_rd) ^ x5_re;
    assign out = x5 ^ {key[50:0], key[63:51]};
endmodule
