#include <stdint.h>
/* fz13_chi5a: generated by gen_fused13.py */
static inline uint64_t rotl64(uint64_t x, unsigned r) {
    r &= 63; return r ? (x << r) | (x >> (64 - r)) : x; }
uint64_t mix_hash(uint64_t v, uint64_t k) {
    uint64_t x = v ^ k;
    { uint64_t r[] = {1, 2, 13};
      x = x ^ (rotl64(x,r[0]) & rotl64(x,r[1])) ^ rotl64(x,r[2]); }
    { uint64_t r[] = {7, 19, 5};
      x = x ^ (rotl64(x,r[0]) & rotl64(x,r[1])) ^ rotl64(x,r[2]); }
    { uint64_t r[] = {3, 11, 29};
      x = x ^ (rotl64(x,r[0]) & rotl64(x,r[1])) ^ rotl64(x,r[2]); }
    { uint64_t r[] = {17, 31, 7};
      x = x ^ (rotl64(x,r[0]) & rotl64(x,r[1])) ^ rotl64(x,r[2]); }
    { uint64_t r[] = {11, 23, 37};
      x = x ^ (rotl64(x,r[0]) & rotl64(x,r[1])) ^ rotl64(x,r[2]); }
    x = x ^ rotl64(k, 13);
    return x;
}
