"""Fused wave-13 candidate fz13_chi5a: 5-stage plain chi control: x ^= (ra&rb)^rc (generated by gen_fused13.py)."""
import numpy as np

M64 = np.uint64(0xFFFFFFFFFFFFFFFF)
RC = np.array([0x9e3779b97f4a7c15, 0x3c6ef372fe94f82a, 0xdaa66d2c7ddf743f, 0x78dde6e5fd29f054, 0x2545f4914f6cdd1d, 0x9e3779b9a1e7c2fa, 0x3c6ef372eca0ae52, 0xdaa66d2cd6129b3e, 0x78dde6e5a883a5fe, 0x2545f4914063d212, 0x9e3779b98fba8ce5, 0x3c6ef372fe6bf8d5], dtype=np.uint64)
def _rotl(x, r):
    r %= 64
    return ((x << np.uint64(r)) | (x >> np.uint64(64 - r))) & M64 if r else x
STAGES = [
    (1, 2, 13),
    (7, 19, 5),
    (3, 11, 29),
    (17, 31, 7),
    (11, 23, 37),
]
def mix_np(V, K):
    x = np.asarray(V, dtype=np.uint64); k = np.asarray(K, dtype=np.uint64)
    x = (x ^ k) & M64
    x = (x ^ (_rotl(x,1) & _rotl(x,2)) ^ _rotl(x,13)) & M64
    x = (x ^ (_rotl(x,7) & _rotl(x,19)) ^ _rotl(x,5)) & M64
    x = (x ^ (_rotl(x,3) & _rotl(x,11)) ^ _rotl(x,29)) & M64
    x = (x ^ (_rotl(x,17) & _rotl(x,31)) ^ _rotl(x,7)) & M64
    x = (x ^ (_rotl(x,11) & _rotl(x,23)) ^ _rotl(x,37)) & M64
    x = (x ^ _rotl(k, 13)) & M64
    return x & M64
def mix(v, k):
    return int(mix_np(np.uint64(v), np.uint64(k)))
