// al_trichi4: 4-stage triple-chi: x ^= ((~ra)&rb)^((~rc)&rd)^((~re)&rf)^rg (fan-in 7) (generated by gen_wave1.py)
module al_trichi4(
    input [63:0] val,
    input [63:0] key,
    output [63:0] out
);
    wire [63:0] x0 = val ^ key;
    wire [63:0] s0a = {x0[62:0], x0[63:63]};
    wire [63:0] s0b = {x0[61:0], x0[63:62]};
    wire [63:0] s0c = {x0[59:0], x0[63:60]};
    wire [63:0] s0d = {x0[55:0], x0[63:56]};
    wire [63:0] s0e = {x0[47:0], x0[63:48]};
    wire [63:0] s0f = {x0[31:0], x0[63:32]};
    wire [63:0] s0g = {x0[56:0], x0[63:57]};
    wire [63:0] x1 = x0 ^ ((~s0a) & s0b) ^ ((~s0c) & s0d) ^ ((~s0e) & s0f) ^ s0g;
    wire [63:0] s1a = {x1[60:0], x1[63:61]};
    wire [63:0] s1b = {x1[54:0], x1[63:55]};
    wire [63:0] s1c = {x1[50:0], x1[63:51]};
    wire [63:0] s1d = {x1[44:0], x1[63:45]};
    wire [63:0] s1e = {x1[34:0], x1[63:35]};
    wire [63:0] s1f = {x1[58:0], x1[63:59]};
    wire [63:0] s1g = {x1[52:0], x1[63:53]};
    wire [63:0] x2 = x1 ^ ((~s1a) & s1b) ^ ((~s1c) & s1d) ^ ((~s1e) & s1f) ^ s1g;
    wire [63:0] s2a = {x2[52:0], x2[63:53]};
    wire [63:0] s2b = {x2[46:0], x2[63:47]};
    wire [63:0] s2c = {x2[40:0], x2[63:41]};
    wire [63:0] s2d = {x2[32:0], x2[63:33]};
    wire [63:0] s2e = {x2[22:0], x2[63:23]};
    wire [63:0] s2f = {x2[50:0], x2[63:51]};
    wire [63:0] s2g = {x2[46:0], x2[63:47]};
    wire [63:0] x3 = x2 ^ ((~s2a) & s2b) ^ ((~s2c) & s2d) ^ ((~s2e) & s2f) ^ s2g;
    wire [63:0] s3a = {x3[58:0], x3[63:59]};
    wire [63:0] s3b = {x3[48:0], x3[63:49]};
    wire [63:0] s3c = {x3[38:0], x3[63:39]};
    wire [63:0] s3d = {x3[26:0], x3[63:27]};
    wire [63:0] s3e = {x3[16:0], x3[63:17]};
    wire [63:0] s3f = {x3[56:0], x3[63:57]};
    wire [63:0] s3g = {x3[40:0], x3[63:41]};
    wire [63:0] x4 = x3 ^ ((~s3a) & s3b) ^ ((~s3c) & s3d) ^ ((~s3e) & s3f) ^ s3g;
    wire [63:0] kr = {key[50:0], key[63:51]};
    assign out = x4 ^ kr;
endmodule
