// hyb18_dual_a: 5-stage [t3,and,and,and,dual]: dual-last-stage breaks wall, proxy z=6.0, est 19.55u (generated by hybrid/batch18/gen_batch18.py)
#include <stdint.h>
static inline uint64_t rotl64(uint64_t x, int r) {
    r &= 63;
    return r ? (x << r) | (x >> (64 - r)) : x;
}
uint64_t mix_hash(uint64_t val, uint64_t key) {
    uint64_t x = val ^ key;
    { /* T3 stage 0 */
        uint64_t ra=rotl64(x,19),rb=rotl64(x,18),rc=rotl64(x,9),re=rotl64(x,7);
        x ^= (ra & rb) ^ rc ^ re;
    }
    { /* AND stage 1 */
        uint64_t ra=rotl64(x,21),rb=rotl64(x,39),rc=rotl64(x,56);
        x ^= (ra & rb) ^ rc;
    }
    { /* AND stage 2 */
        uint64_t ra=rotl64(x,15),rb=rotl64(x,59),rc=rotl64(x,38);
        x ^= (ra & rb) ^ rc;
    }
    { /* AND stage 3 */
        uint64_t ra=rotl64(x,51),rb=rotl64(x,63),rc=rotl64(x,56);
        x ^= (ra & rb) ^ rc;
    }
    { /* DUAL stage 4 */
        uint64_t ra=rotl64(x,10),rb=rotl64(x,5),rc=rotl64(x,55),rd=rotl64(x,41),re=rotl64(x,3);
        x ^= (ra & rb) ^ (rc & rd) ^ re;
    }
    return x ^ rotl64(key, 13);
}
