// hyb18_dual_a: 5-stage [t3,and,and,and,dual]: dual-last-stage breaks wall, proxy z=6.0, est 19.55u (generated by hybrid/batch18/gen_batch18.py)
module mix_hash(input [63:0] val, input [63:0] key, output [63:0] out);
    wire [63:0] x0 = val ^ key;
    wire [63:0] x1_ra = {x0[44:0], x0[63:45]};
    wire [63:0] x1_rb = {x0[45:0], x0[63:46]};
    wire [63:0] x1_rc = {x0[54:0], x0[63:55]};
    wire [63:0] x1_re = {x0[56:0], x0[63:57]};
    wire [63:0] x1 = x0 ^ (x1_ra & x1_rb) ^ x1_rc ^ x1_re;
    wire [63:0] x2_ra = {x1[42:0], x1[63:43]};
    wire [63:0] x2_rb = {x1[24:0], x1[63:25]};
    wire [63:0] x2_rc = {x1[7:0], x1[63:8]};
    wire [63:0] x2 = x1 ^ (x2_ra & x2_rb) ^ x2_rc;
    wire [63:0] x3_ra = {x2[48:0], x2[63:49]};
    wire [63:0] x3_rb = {x2[4:0], x2[63:5]};
    wire [63:0] x3_rc = {x2[25:0], x2[63:26]};
    wire [63:0] x3 = x2 ^ (x3_ra & x3_rb) ^ x3_rc;
    wire [63:0] x4_ra = {x3[12:0], x3[63:13]};
    wire [63:0] x4_rb = {x3[0:0], x3[63:1]};
    wire [63:0] x4_rc = {x3[7:0], x3[63:8]};
    wire [63:0] x4 = x3 ^ (x4_ra & x4_rb) ^ x4_rc;
    wire [63:0] x5_ra = {x4[53:0], x4[63:54]};
    wire [63:0] x5_rb = {x4[58:0], x4[63:59]};
    wire [63:0] x5_rc = {x4[8:0], x4[63:9]};
    wire [63:0] x5_rd = {x4[22:0], x4[63:23]};
    wire [63:0] x5_re = {x4[60:0], x4[63:61]};
    wire [63:0] x5 = x4 ^ (x5_ra & x5_rb) ^ (x5_rc & x5_rd) ^ x5_re;
    assign out = x5 ^ {key[50:0], key[63:51]};
endmodule
