// al_chi6e: 6-stage chi cascade, avalanche-aware schedule E (random well-separated) (generated by gen_wave1.py)
module al_chi6e(
    input [63:0] v,
    input [63:0] k,
    output [63:0] o
);
    wire [63:0] x0 = v ^ k;
    wire [63:0] s0a = {x0[43:0], x0[63:44]};
    wire [63:0] s0b = {x0[35:0], x0[63:36]};
    wire [63:0] s0c = {x0[28:0], x0[63:29]};
    wire [63:0] x1 = x0 ^ ((~s0a) & s0b) ^ s0c;
    wire [63:0] s1a = {x1[52:0], x1[63:53]};
    wire [63:0] s1b = {x1[59:0], x1[63:60]};
    wire [63:0] s1c = {x1[17:0], x1[63:18]};
    wire [63:0] x2 = x1 ^ ((~s1a) & s1b) ^ s1c;
    wire [63:0] s2a = {x2[7:0], x2[63:8]};
    wire [63:0] s2b = {x2[20:0], x2[63:21]};
    wire [63:0] s2c = {x2[47:0], x2[63:48]};
    wire [63:0] x3 = x2 ^ ((~s2a) & s2b) ^ s2c;
    wire [63:0] s3a = {x3[46:0], x3[63:47]};
    wire [63:0] s3b = {x3[13:0], x3[63:14]};
    wire [63:0] s3c = {x3[58:0], x3[63:59]};
    wire [63:0] x4 = x3 ^ ((~s3a) & s3b) ^ s3c;
    wire [63:0] s4a = {x4[19:0], x4[63:20]};
    wire [63:0] s4b = {x4[34:0], x4[63:35]};
    wire [63:0] s4c = {x4[1:0], x4[63:2]};
    wire [63:0] x5 = x4 ^ ((~s4a) & s4b) ^ s4c;
    wire [63:0] s5a = {x5[27:0], x5[63:28]};
    wire [63:0] s5b = {x5[9:0], x5[63:10]};
    wire [63:0] s5c = {x5[2:0], x5[63:3]};
    wire [63:0] x6 = x5 ^ ((~s5a) & s5b) ^ s5c;
    wire [63:0] kr = {k[50:0], k[63:51]};
    assign o = x6 ^ kr;
endmodule
