// as6_200_118: and6 sched search as6_200_118 z=7.1 (generated by gen_waveP.py)
module as6_200_118(
    input [63:0] val,
    input [63:0] key,
    output [63:0] out
);
    function [3:0] sbox4(input [3:0] v);
        case (v)
            4'h0: sbox4 = 4'hC;
            4'h1: sbox4 = 4'h6;
            4'h2: sbox4 = 4'h9;
            4'h3: sbox4 = 4'h0;
            4'h4: sbox4 = 4'h1;
            4'h5: sbox4 = 4'hA;
            4'h6: sbox4 = 4'h7;
            4'h7: sbox4 = 4'hB;
            4'h8: sbox4 = 4'h3;
            4'h9: sbox4 = 4'hE;
            4'hA: sbox4 = 4'hF;
            4'hB: sbox4 = 4'h8;
            4'hC: sbox4 = 4'h4;
            4'hD: sbox4 = 4'hD;
            4'hE: sbox4 = 4'h5;
            4'hF: sbox4 = 4'h2;
        endcase
    endfunction
    wire [63:0] x0 = val ^ key;
    wire [63:0] x1 = x0 ^ ({x0[57:0], x0[63:58]} & {x0[31:0], x0[63:32]}) ^ {x0[3:0], x0[63:4]};
    wire [63:0] x2 = x1 ^ ({x1[50:0], x1[63:51]} & {x1[40:0], x1[63:41]}) ^ {x1[14:0], x1[63:15]};
    wire [63:0] x3 = x2 ^ ({x2[60:0], x2[63:61]} & {x2[25:0], x2[63:26]}) ^ {x2[32:0], x2[63:33]};
    wire [63:0] x4 = x3 ^ ({x3[25:0], x3[63:26]} & {x3[21:0], x3[63:22]}) ^ {x3[31:0], x3[63:32]};
    wire [63:0] x5 = x4 ^ ({x4[61:0], x4[63:62]} & {x4[9:0], x4[63:10]}) ^ {x4[25:0], x4[63:26]};
    wire [63:0] x6 = x5 ^ ({x5[60:0], x5[63:61]} & {x5[17:0], x5[63:18]}) ^ {x5[36:0], x5[63:37]};
    wire [63:0] kr = {key[50:0], key[63:51]};
    assign out = x6 ^ kr;
endmodule
