// hyb11_and5_finalPL: 5-stage al_and6a triplets + final P(37,1)+L(5,13): can final diffusion replace stage 6? (generated by hybrid/codesign/gen_batch11.py)
module hyb11_and5_finalPL(
    input [63:0] val,
    input [63:0] key,
    output [63:0] out
);
    wire [63:0] x0 = val ^ key;
    wire [63:0] s0a = {x0[62:0], x0[63:63]};
    wire [63:0] s0b = {x0[61:0], x0[63:62]};
    wire [63:0] s0c = {x0[50:0], x0[63:51]};
    wire [63:0] t0 = x0 ^ (s0a & s0b) ^ s0c;
    wire [63:0] s1a = {t0[56:0], t0[63:57]};
    wire [63:0] s1b = {t0[44:0], t0[63:45]};
    wire [63:0] s1c = {t0[58:0], t0[63:59]};
    wire [63:0] t1 = t0 ^ (s1a & s1b) ^ s1c;
    wire [63:0] s2a = {t1[60:0], t1[63:61]};
    wire [63:0] s2b = {t1[52:0], t1[63:53]};
    wire [63:0] s2c = {t1[34:0], t1[63:35]};
    wire [63:0] t2 = t1 ^ (s2a & s2b) ^ s2c;
    wire [63:0] s3a = {t2[46:0], t2[63:47]};
    wire [63:0] s3b = {t2[32:0], t2[63:33]};
    wire [63:0] s3c = {t2[56:0], t2[63:57]};
    wire [63:0] t3 = t2 ^ (s3a & s3b) ^ s3c;
    wire [63:0] s4a = {t3[52:0], t3[63:53]};
    wire [63:0] s4b = {t3[40:0], t3[63:41]};
    wire [63:0] s4c = {t3[26:0], t3[63:27]};
    wire [63:0] t4 = t3 ^ (s4a & s4b) ^ s4c;
    wire [63:0] pf = {t4[38], t4[57], t4[12], t4[31], t4[50], t4[5], t4[24], t4[43], t4[62], t4[17], t4[36], t4[55], t4[10], t4[29], t4[48], t4[3], t4[22], t4[41], t4[60], t4[15], t4[34], t4[53], t4[8], t4[27], t4[46], t4[1], t4[20], t4[39], t4[58], t4[13], t4[32], t4[51], t4[6], t4[25], t4[44], t4[63], t4[18], t4[37], t4[56], t4[11], t4[30], t4[49], t4[4], t4[23], t4[42], t4[61], t4[16], t4[35], t4[54], t4[9], t4[28], t4[47], t4[2], t4[21], t4[40], t4[59], t4[14], t4[33], t4[52], t4[7], t4[26], t4[45], t4[0], t4[19]};
    wire [63:0] lf = pf ^ {pf[58:0], pf[63:59]} ^ {pf[50:0], pf[63:51]};
    wire [63:0] kr = {key[50:0], key[63:51]};
    assign out = lf ^ kr;
endmodule
