"""Self-contained numpy model for dd9_scsc_nolin_b (generated by mk_model.py, mixed layers).

Construction (matches directed_design/gen_verilog.py gen_mixed_verilog):
  round i: x = LIN?(P(NL_i(x ^ rk_i)))
  NL_i = SBOX (nibble table) | chi: x ^ (rotl(x,a)&rotl(x,b)) ^ rotl(x,c)  [and]
                                 x ^ (rotl(x,a)&~rotl(x,b)) ^ rotl(x,c) [keccak]
  P: out[P[i]] = in[i]
  LIN (where enabled): x ^ rotl64(x,5) ^ rotl64(x,13)
  rk_i = rk_i = rotl64(key,13*(i+1)) ^ RC[i]
  pattern: SCSC
"""
import numpy as np

M64 = np.uint64(0xFFFFFFFFFFFFFFFF)
SBOXES = {'R': [0, 1, 2, 3, 4, 6, 8, 11, 13, 9, 7, 15, 12, 10, 5, 14]}
PBOX = [1, 20, 39, 58, 13, 32, 51, 6, 25, 44, 63, 18, 37, 56, 11, 30, 49, 4, 23, 42, 61, 16, 35, 54, 9, 28, 47, 2, 21, 40, 59, 14, 33, 52, 7, 26, 45, 0, 19, 38, 57, 12, 31, 50, 5, 24, 43, 62, 17, 36, 55, 10, 29, 48, 3, 22, 41, 60, 15, 34, 53, 8, 27, 46]
RC = np.array([11400714819323198485, 4354685564936845354, 15755400384260043839, 8709371129873690708], dtype=np.uint64)
ROUNDS = 4
# LAYERS[i] = ("sbox", sbox_key) | ("chi", (a,b,c), flavor) ; LIN_ON[i] bool
LAYERS = [('sbox', 'R'), ('chi', (17, 31, 7), 'and'), ('sbox', 'R'), ('chi', (11, 23, 37), 'and')]
LIN_ON = [False, False, False, False]
KS_ROT_STEPS = [13]


def _rotl(x, r):
    r %= 64
    if r == 0:
        return x
    return ((x << np.uint64(r)) | (x >> np.uint64(64 - r))) & M64


def _sbox64(x, key):
    sb = np.array(SBOXES[key], dtype=np.uint64)
    y = np.zeros_like(x)
    for i in range(16):
        y |= sb[((x >> np.uint64(4 * i)) & np.uint64(0xF))] << np.uint64(4 * i)
    return y & M64


def _chi(x, a, b, c, flavor):
    ra, rb, rc = _rotl(x, a), _rotl(x, b), _rotl(x, c)
    if flavor == "and":
        return (x ^ (ra & rb) ^ rc) & M64
    if flavor == "keccak":
        return (x ^ (ra & ((~rb) & M64)) ^ rc) & M64
    raise ValueError(flavor)


def _pbox64(x):
    y = np.zeros_like(x)
    for i in range(64):
        y |= ((x >> np.uint64(i)) & np.uint64(1)) << np.uint64(PBOX[i])
    return y & M64


def _lin(x):
    return (x ^ _rotl(x, 5) ^ _rotl(x, 13)) & M64


def _round(x, key, i):
    rk = np.uint64(0)
    for s in KS_ROT_STEPS:
        rk ^= _rotl(key, s * (i + 1))
    rk ^= RC[i]
    t = x ^ rk
    typ = LAYERS[i][0]
    if typ == "sbox":
        y = _sbox64(t, LAYERS[i][1])
    elif typ == "chi":
        (a, b, c), flavor = LAYERS[i][1], LAYERS[i][2]
        y = _chi(t, a, b, c, flavor)
    else:
        raise ValueError(typ)
    z = _pbox64(y)
    if LIN_ON[i]:
        z = _lin(z)
    return z


def mix_np(V, K):
    x = np.asarray(V, dtype=np.uint64)
    k = np.asarray(K, dtype=np.uint64)
    for i in range(ROUNDS):
        x = _round(x, k, i)
    return x & M64


def mix(v, k):
    return int(mix_np(np.uint64(v), np.uint64(k)))
