// dd6_kssmallrc_lin5_9_nw: 4r SPN, rasC2_0, pba19, LIN=lin(5,9)
// GENERATED by directed_design/gen_verilog.py
module dd6_kssmallrc_lin5_9_nw(
  input [63:0] val,
  input [63:0] key,
  output [63:0] out
);

  // Key schedule: rk_i = rotl(key,13*(i+1)) ^ RC[i]
  wire [63:0] rk0 = ({key[50:0], key[63:51]}) ^ 64'h0000000000000001;
  wire [63:0] rk1 = ({key[37:0], key[63:38]}) ^ 64'h0000000000000002;
  wire [63:0] rk2 = ({key[24:0], key[63:25]}) ^ 64'h0000000000000003;
  wire [63:0] rk3 = ({key[11:0], key[63:12]}) ^ 64'h0000000000000004;

  // Round 0
  wire [63:0] x0_xor = val ^ rk0;

  reg [63:0] x0_sbox_r;
  always @(*) begin
    x0_sbox_r = 64'h0;
    case (x0_xor[3:0])
      4'h0: x0_sbox_r[3:0] = 4'h0;
      4'h1: x0_sbox_r[3:0] = 4'h1;
      4'h2: x0_sbox_r[3:0] = 4'h2;
      4'h3: x0_sbox_r[3:0] = 4'h3;
      4'h4: x0_sbox_r[3:0] = 4'h4;
      4'h5: x0_sbox_r[3:0] = 4'h6;
      4'h6: x0_sbox_r[3:0] = 4'h8;
      4'h7: x0_sbox_r[3:0] = 4'hb;
      4'h8: x0_sbox_r[3:0] = 4'hd;
      4'h9: x0_sbox_r[3:0] = 4'h9;
      4'ha: x0_sbox_r[3:0] = 4'h7;
      4'hb: x0_sbox_r[3:0] = 4'hf;
      4'hc: x0_sbox_r[3:0] = 4'hc;
      4'hd: x0_sbox_r[3:0] = 4'ha;
      4'he: x0_sbox_r[3:0] = 4'h5;
      4'hf: x0_sbox_r[3:0] = 4'he;
    endcase
    case (x0_xor[7:4])
      4'h0: x0_sbox_r[7:4] = 4'h0;
      4'h1: x0_sbox_r[7:4] = 4'h1;
      4'h2: x0_sbox_r[7:4] = 4'h2;
      4'h3: x0_sbox_r[7:4] = 4'h3;
      4'h4: x0_sbox_r[7:4] = 4'h4;
      4'h5: x0_sbox_r[7:4] = 4'h6;
      4'h6: x0_sbox_r[7:4] = 4'h8;
      4'h7: x0_sbox_r[7:4] = 4'hb;
      4'h8: x0_sbox_r[7:4] = 4'hd;
      4'h9: x0_sbox_r[7:4] = 4'h9;
      4'ha: x0_sbox_r[7:4] = 4'h7;
      4'hb: x0_sbox_r[7:4] = 4'hf;
      4'hc: x0_sbox_r[7:4] = 4'hc;
      4'hd: x0_sbox_r[7:4] = 4'ha;
      4'he: x0_sbox_r[7:4] = 4'h5;
      4'hf: x0_sbox_r[7:4] = 4'he;
    endcase
    case (x0_xor[11:8])
      4'h0: x0_sbox_r[11:8] = 4'h0;
      4'h1: x0_sbox_r[11:8] = 4'h1;
      4'h2: x0_sbox_r[11:8] = 4'h2;
      4'h3: x0_sbox_r[11:8] = 4'h3;
      4'h4: x0_sbox_r[11:8] = 4'h4;
      4'h5: x0_sbox_r[11:8] = 4'h6;
      4'h6: x0_sbox_r[11:8] = 4'h8;
      4'h7: x0_sbox_r[11:8] = 4'hb;
      4'h8: x0_sbox_r[11:8] = 4'hd;
      4'h9: x0_sbox_r[11:8] = 4'h9;
      4'ha: x0_sbox_r[11:8] = 4'h7;
      4'hb: x0_sbox_r[11:8] = 4'hf;
      4'hc: x0_sbox_r[11:8] = 4'hc;
      4'hd: x0_sbox_r[11:8] = 4'ha;
      4'he: x0_sbox_r[11:8] = 4'h5;
      4'hf: x0_sbox_r[11:8] = 4'he;
    endcase
    case (x0_xor[15:12])
      4'h0: x0_sbox_r[15:12] = 4'h0;
      4'h1: x0_sbox_r[15:12] = 4'h1;
      4'h2: x0_sbox_r[15:12] = 4'h2;
      4'h3: x0_sbox_r[15:12] = 4'h3;
      4'h4: x0_sbox_r[15:12] = 4'h4;
      4'h5: x0_sbox_r[15:12] = 4'h6;
      4'h6: x0_sbox_r[15:12] = 4'h8;
      4'h7: x0_sbox_r[15:12] = 4'hb;
      4'h8: x0_sbox_r[15:12] = 4'hd;
      4'h9: x0_sbox_r[15:12] = 4'h9;
      4'ha: x0_sbox_r[15:12] = 4'h7;
      4'hb: x0_sbox_r[15:12] = 4'hf;
      4'hc: x0_sbox_r[15:12] = 4'hc;
      4'hd: x0_sbox_r[15:12] = 4'ha;
      4'he: x0_sbox_r[15:12] = 4'h5;
      4'hf: x0_sbox_r[15:12] = 4'he;
    endcase
    case (x0_xor[19:16])
      4'h0: x0_sbox_r[19:16] = 4'h0;
      4'h1: x0_sbox_r[19:16] = 4'h1;
      4'h2: x0_sbox_r[19:16] = 4'h2;
      4'h3: x0_sbox_r[19:16] = 4'h3;
      4'h4: x0_sbox_r[19:16] = 4'h4;
      4'h5: x0_sbox_r[19:16] = 4'h6;
      4'h6: x0_sbox_r[19:16] = 4'h8;
      4'h7: x0_sbox_r[19:16] = 4'hb;
      4'h8: x0_sbox_r[19:16] = 4'hd;
      4'h9: x0_sbox_r[19:16] = 4'h9;
      4'ha: x0_sbox_r[19:16] = 4'h7;
      4'hb: x0_sbox_r[19:16] = 4'hf;
      4'hc: x0_sbox_r[19:16] = 4'hc;
      4'hd: x0_sbox_r[19:16] = 4'ha;
      4'he: x0_sbox_r[19:16] = 4'h5;
      4'hf: x0_sbox_r[19:16] = 4'he;
    endcase
    case (x0_xor[23:20])
      4'h0: x0_sbox_r[23:20] = 4'h0;
      4'h1: x0_sbox_r[23:20] = 4'h1;
      4'h2: x0_sbox_r[23:20] = 4'h2;
      4'h3: x0_sbox_r[23:20] = 4'h3;
      4'h4: x0_sbox_r[23:20] = 4'h4;
      4'h5: x0_sbox_r[23:20] = 4'h6;
      4'h6: x0_sbox_r[23:20] = 4'h8;
      4'h7: x0_sbox_r[23:20] = 4'hb;
      4'h8: x0_sbox_r[23:20] = 4'hd;
      4'h9: x0_sbox_r[23:20] = 4'h9;
      4'ha: x0_sbox_r[23:20] = 4'h7;
      4'hb: x0_sbox_r[23:20] = 4'hf;
      4'hc: x0_sbox_r[23:20] = 4'hc;
      4'hd: x0_sbox_r[23:20] = 4'ha;
      4'he: x0_sbox_r[23:20] = 4'h5;
      4'hf: x0_sbox_r[23:20] = 4'he;
    endcase
    case (x0_xor[27:24])
      4'h0: x0_sbox_r[27:24] = 4'h0;
      4'h1: x0_sbox_r[27:24] = 4'h1;
      4'h2: x0_sbox_r[27:24] = 4'h2;
      4'h3: x0_sbox_r[27:24] = 4'h3;
      4'h4: x0_sbox_r[27:24] = 4'h4;
      4'h5: x0_sbox_r[27:24] = 4'h6;
      4'h6: x0_sbox_r[27:24] = 4'h8;
      4'h7: x0_sbox_r[27:24] = 4'hb;
      4'h8: x0_sbox_r[27:24] = 4'hd;
      4'h9: x0_sbox_r[27:24] = 4'h9;
      4'ha: x0_sbox_r[27:24] = 4'h7;
      4'hb: x0_sbox_r[27:24] = 4'hf;
      4'hc: x0_sbox_r[27:24] = 4'hc;
      4'hd: x0_sbox_r[27:24] = 4'ha;
      4'he: x0_sbox_r[27:24] = 4'h5;
      4'hf: x0_sbox_r[27:24] = 4'he;
    endcase
    case (x0_xor[31:28])
      4'h0: x0_sbox_r[31:28] = 4'h0;
      4'h1: x0_sbox_r[31:28] = 4'h1;
      4'h2: x0_sbox_r[31:28] = 4'h2;
      4'h3: x0_sbox_r[31:28] = 4'h3;
      4'h4: x0_sbox_r[31:28] = 4'h4;
      4'h5: x0_sbox_r[31:28] = 4'h6;
      4'h6: x0_sbox_r[31:28] = 4'h8;
      4'h7: x0_sbox_r[31:28] = 4'hb;
      4'h8: x0_sbox_r[31:28] = 4'hd;
      4'h9: x0_sbox_r[31:28] = 4'h9;
      4'ha: x0_sbox_r[31:28] = 4'h7;
      4'hb: x0_sbox_r[31:28] = 4'hf;
      4'hc: x0_sbox_r[31:28] = 4'hc;
      4'hd: x0_sbox_r[31:28] = 4'ha;
      4'he: x0_sbox_r[31:28] = 4'h5;
      4'hf: x0_sbox_r[31:28] = 4'he;
    endcase
    case (x0_xor[35:32])
      4'h0: x0_sbox_r[35:32] = 4'h0;
      4'h1: x0_sbox_r[35:32] = 4'h1;
      4'h2: x0_sbox_r[35:32] = 4'h2;
      4'h3: x0_sbox_r[35:32] = 4'h3;
      4'h4: x0_sbox_r[35:32] = 4'h4;
      4'h5: x0_sbox_r[35:32] = 4'h6;
      4'h6: x0_sbox_r[35:32] = 4'h8;
      4'h7: x0_sbox_r[35:32] = 4'hb;
      4'h8: x0_sbox_r[35:32] = 4'hd;
      4'h9: x0_sbox_r[35:32] = 4'h9;
      4'ha: x0_sbox_r[35:32] = 4'h7;
      4'hb: x0_sbox_r[35:32] = 4'hf;
      4'hc: x0_sbox_r[35:32] = 4'hc;
      4'hd: x0_sbox_r[35:32] = 4'ha;
      4'he: x0_sbox_r[35:32] = 4'h5;
      4'hf: x0_sbox_r[35:32] = 4'he;
    endcase
    case (x0_xor[39:36])
      4'h0: x0_sbox_r[39:36] = 4'h0;
      4'h1: x0_sbox_r[39:36] = 4'h1;
      4'h2: x0_sbox_r[39:36] = 4'h2;
      4'h3: x0_sbox_r[39:36] = 4'h3;
      4'h4: x0_sbox_r[39:36] = 4'h4;
      4'h5: x0_sbox_r[39:36] = 4'h6;
      4'h6: x0_sbox_r[39:36] = 4'h8;
      4'h7: x0_sbox_r[39:36] = 4'hb;
      4'h8: x0_sbox_r[39:36] = 4'hd;
      4'h9: x0_sbox_r[39:36] = 4'h9;
      4'ha: x0_sbox_r[39:36] = 4'h7;
      4'hb: x0_sbox_r[39:36] = 4'hf;
      4'hc: x0_sbox_r[39:36] = 4'hc;
      4'hd: x0_sbox_r[39:36] = 4'ha;
      4'he: x0_sbox_r[39:36] = 4'h5;
      4'hf: x0_sbox_r[39:36] = 4'he;
    endcase
    case (x0_xor[43:40])
      4'h0: x0_sbox_r[43:40] = 4'h0;
      4'h1: x0_sbox_r[43:40] = 4'h1;
      4'h2: x0_sbox_r[43:40] = 4'h2;
      4'h3: x0_sbox_r[43:40] = 4'h3;
      4'h4: x0_sbox_r[43:40] = 4'h4;
      4'h5: x0_sbox_r[43:40] = 4'h6;
      4'h6: x0_sbox_r[43:40] = 4'h8;
      4'h7: x0_sbox_r[43:40] = 4'hb;
      4'h8: x0_sbox_r[43:40] = 4'hd;
      4'h9: x0_sbox_r[43:40] = 4'h9;
      4'ha: x0_sbox_r[43:40] = 4'h7;
      4'hb: x0_sbox_r[43:40] = 4'hf;
      4'hc: x0_sbox_r[43:40] = 4'hc;
      4'hd: x0_sbox_r[43:40] = 4'ha;
      4'he: x0_sbox_r[43:40] = 4'h5;
      4'hf: x0_sbox_r[43:40] = 4'he;
    endcase
    case (x0_xor[47:44])
      4'h0: x0_sbox_r[47:44] = 4'h0;
      4'h1: x0_sbox_r[47:44] = 4'h1;
      4'h2: x0_sbox_r[47:44] = 4'h2;
      4'h3: x0_sbox_r[47:44] = 4'h3;
      4'h4: x0_sbox_r[47:44] = 4'h4;
      4'h5: x0_sbox_r[47:44] = 4'h6;
      4'h6: x0_sbox_r[47:44] = 4'h8;
      4'h7: x0_sbox_r[47:44] = 4'hb;
      4'h8: x0_sbox_r[47:44] = 4'hd;
      4'h9: x0_sbox_r[47:44] = 4'h9;
      4'ha: x0_sbox_r[47:44] = 4'h7;
      4'hb: x0_sbox_r[47:44] = 4'hf;
      4'hc: x0_sbox_r[47:44] = 4'hc;
      4'hd: x0_sbox_r[47:44] = 4'ha;
      4'he: x0_sbox_r[47:44] = 4'h5;
      4'hf: x0_sbox_r[47:44] = 4'he;
    endcase
    case (x0_xor[51:48])
      4'h0: x0_sbox_r[51:48] = 4'h0;
      4'h1: x0_sbox_r[51:48] = 4'h1;
      4'h2: x0_sbox_r[51:48] = 4'h2;
      4'h3: x0_sbox_r[51:48] = 4'h3;
      4'h4: x0_sbox_r[51:48] = 4'h4;
      4'h5: x0_sbox_r[51:48] = 4'h6;
      4'h6: x0_sbox_r[51:48] = 4'h8;
      4'h7: x0_sbox_r[51:48] = 4'hb;
      4'h8: x0_sbox_r[51:48] = 4'hd;
      4'h9: x0_sbox_r[51:48] = 4'h9;
      4'ha: x0_sbox_r[51:48] = 4'h7;
      4'hb: x0_sbox_r[51:48] = 4'hf;
      4'hc: x0_sbox_r[51:48] = 4'hc;
      4'hd: x0_sbox_r[51:48] = 4'ha;
      4'he: x0_sbox_r[51:48] = 4'h5;
      4'hf: x0_sbox_r[51:48] = 4'he;
    endcase
    case (x0_xor[55:52])
      4'h0: x0_sbox_r[55:52] = 4'h0;
      4'h1: x0_sbox_r[55:52] = 4'h1;
      4'h2: x0_sbox_r[55:52] = 4'h2;
      4'h3: x0_sbox_r[55:52] = 4'h3;
      4'h4: x0_sbox_r[55:52] = 4'h4;
      4'h5: x0_sbox_r[55:52] = 4'h6;
      4'h6: x0_sbox_r[55:52] = 4'h8;
      4'h7: x0_sbox_r[55:52] = 4'hb;
      4'h8: x0_sbox_r[55:52] = 4'hd;
      4'h9: x0_sbox_r[55:52] = 4'h9;
      4'ha: x0_sbox_r[55:52] = 4'h7;
      4'hb: x0_sbox_r[55:52] = 4'hf;
      4'hc: x0_sbox_r[55:52] = 4'hc;
      4'hd: x0_sbox_r[55:52] = 4'ha;
      4'he: x0_sbox_r[55:52] = 4'h5;
      4'hf: x0_sbox_r[55:52] = 4'he;
    endcase
    case (x0_xor[59:56])
      4'h0: x0_sbox_r[59:56] = 4'h0;
      4'h1: x0_sbox_r[59:56] = 4'h1;
      4'h2: x0_sbox_r[59:56] = 4'h2;
      4'h3: x0_sbox_r[59:56] = 4'h3;
      4'h4: x0_sbox_r[59:56] = 4'h4;
      4'h5: x0_sbox_r[59:56] = 4'h6;
      4'h6: x0_sbox_r[59:56] = 4'h8;
      4'h7: x0_sbox_r[59:56] = 4'hb;
      4'h8: x0_sbox_r[59:56] = 4'hd;
      4'h9: x0_sbox_r[59:56] = 4'h9;
      4'ha: x0_sbox_r[59:56] = 4'h7;
      4'hb: x0_sbox_r[59:56] = 4'hf;
      4'hc: x0_sbox_r[59:56] = 4'hc;
      4'hd: x0_sbox_r[59:56] = 4'ha;
      4'he: x0_sbox_r[59:56] = 4'h5;
      4'hf: x0_sbox_r[59:56] = 4'he;
    endcase
    case (x0_xor[63:60])
      4'h0: x0_sbox_r[63:60] = 4'h0;
      4'h1: x0_sbox_r[63:60] = 4'h1;
      4'h2: x0_sbox_r[63:60] = 4'h2;
      4'h3: x0_sbox_r[63:60] = 4'h3;
      4'h4: x0_sbox_r[63:60] = 4'h4;
      4'h5: x0_sbox_r[63:60] = 4'h6;
      4'h6: x0_sbox_r[63:60] = 4'h8;
      4'h7: x0_sbox_r[63:60] = 4'hb;
      4'h8: x0_sbox_r[63:60] = 4'hd;
      4'h9: x0_sbox_r[63:60] = 4'h9;
      4'ha: x0_sbox_r[63:60] = 4'h7;
      4'hb: x0_sbox_r[63:60] = 4'hf;
      4'hc: x0_sbox_r[63:60] = 4'hc;
      4'hd: x0_sbox_r[63:60] = 4'ha;
      4'he: x0_sbox_r[63:60] = 4'h5;
      4'hf: x0_sbox_r[63:60] = 4'he;
    endcase
  end
  wire [63:0] x0_sbox = x0_sbox_r;

  wire [63:0] x0_pbox;
  assign x0_pbox[1] = x0_sbox[0];
  assign x0_pbox[20] = x0_sbox[1];
  assign x0_pbox[39] = x0_sbox[2];
  assign x0_pbox[58] = x0_sbox[3];
  assign x0_pbox[13] = x0_sbox[4];
  assign x0_pbox[32] = x0_sbox[5];
  assign x0_pbox[51] = x0_sbox[6];
  assign x0_pbox[6] = x0_sbox[7];
  assign x0_pbox[25] = x0_sbox[8];
  assign x0_pbox[44] = x0_sbox[9];
  assign x0_pbox[63] = x0_sbox[10];
  assign x0_pbox[18] = x0_sbox[11];
  assign x0_pbox[37] = x0_sbox[12];
  assign x0_pbox[56] = x0_sbox[13];
  assign x0_pbox[11] = x0_sbox[14];
  assign x0_pbox[30] = x0_sbox[15];
  assign x0_pbox[49] = x0_sbox[16];
  assign x0_pbox[4] = x0_sbox[17];
  assign x0_pbox[23] = x0_sbox[18];
  assign x0_pbox[42] = x0_sbox[19];
  assign x0_pbox[61] = x0_sbox[20];
  assign x0_pbox[16] = x0_sbox[21];
  assign x0_pbox[35] = x0_sbox[22];
  assign x0_pbox[54] = x0_sbox[23];
  assign x0_pbox[9] = x0_sbox[24];
  assign x0_pbox[28] = x0_sbox[25];
  assign x0_pbox[47] = x0_sbox[26];
  assign x0_pbox[2] = x0_sbox[27];
  assign x0_pbox[21] = x0_sbox[28];
  assign x0_pbox[40] = x0_sbox[29];
  assign x0_pbox[59] = x0_sbox[30];
  assign x0_pbox[14] = x0_sbox[31];
  assign x0_pbox[33] = x0_sbox[32];
  assign x0_pbox[52] = x0_sbox[33];
  assign x0_pbox[7] = x0_sbox[34];
  assign x0_pbox[26] = x0_sbox[35];
  assign x0_pbox[45] = x0_sbox[36];
  assign x0_pbox[0] = x0_sbox[37];
  assign x0_pbox[19] = x0_sbox[38];
  assign x0_pbox[38] = x0_sbox[39];
  assign x0_pbox[57] = x0_sbox[40];
  assign x0_pbox[12] = x0_sbox[41];
  assign x0_pbox[31] = x0_sbox[42];
  assign x0_pbox[50] = x0_sbox[43];
  assign x0_pbox[5] = x0_sbox[44];
  assign x0_pbox[24] = x0_sbox[45];
  assign x0_pbox[43] = x0_sbox[46];
  assign x0_pbox[62] = x0_sbox[47];
  assign x0_pbox[17] = x0_sbox[48];
  assign x0_pbox[36] = x0_sbox[49];
  assign x0_pbox[55] = x0_sbox[50];
  assign x0_pbox[10] = x0_sbox[51];
  assign x0_pbox[29] = x0_sbox[52];
  assign x0_pbox[48] = x0_sbox[53];
  assign x0_pbox[3] = x0_sbox[54];
  assign x0_pbox[22] = x0_sbox[55];
  assign x0_pbox[41] = x0_sbox[56];
  assign x0_pbox[60] = x0_sbox[57];
  assign x0_pbox[15] = x0_sbox[58];
  assign x0_pbox[34] = x0_sbox[59];
  assign x0_pbox[53] = x0_sbox[60];
  assign x0_pbox[8] = x0_sbox[61];
  assign x0_pbox[27] = x0_sbox[62];
  assign x0_pbox[46] = x0_sbox[63];

  wire [63:0] x1 = x0_pbox ^ ({x0_pbox[58:0], x0_pbox[63:59]}) ^ ({x0_pbox[54:0], x0_pbox[63:55]});

  // Round 1
  wire [63:0] x1_xor = x1 ^ rk1;

  reg [63:0] x1_sbox_r;
  always @(*) begin
    x1_sbox_r = 64'h0;
    case (x1_xor[3:0])
      4'h0: x1_sbox_r[3:0] = 4'h0;
      4'h1: x1_sbox_r[3:0] = 4'h1;
      4'h2: x1_sbox_r[3:0] = 4'h2;
      4'h3: x1_sbox_r[3:0] = 4'h3;
      4'h4: x1_sbox_r[3:0] = 4'h4;
      4'h5: x1_sbox_r[3:0] = 4'h6;
      4'h6: x1_sbox_r[3:0] = 4'h8;
      4'h7: x1_sbox_r[3:0] = 4'hb;
      4'h8: x1_sbox_r[3:0] = 4'hd;
      4'h9: x1_sbox_r[3:0] = 4'h9;
      4'ha: x1_sbox_r[3:0] = 4'h7;
      4'hb: x1_sbox_r[3:0] = 4'hf;
      4'hc: x1_sbox_r[3:0] = 4'hc;
      4'hd: x1_sbox_r[3:0] = 4'ha;
      4'he: x1_sbox_r[3:0] = 4'h5;
      4'hf: x1_sbox_r[3:0] = 4'he;
    endcase
    case (x1_xor[7:4])
      4'h0: x1_sbox_r[7:4] = 4'h0;
      4'h1: x1_sbox_r[7:4] = 4'h1;
      4'h2: x1_sbox_r[7:4] = 4'h2;
      4'h3: x1_sbox_r[7:4] = 4'h3;
      4'h4: x1_sbox_r[7:4] = 4'h4;
      4'h5: x1_sbox_r[7:4] = 4'h6;
      4'h6: x1_sbox_r[7:4] = 4'h8;
      4'h7: x1_sbox_r[7:4] = 4'hb;
      4'h8: x1_sbox_r[7:4] = 4'hd;
      4'h9: x1_sbox_r[7:4] = 4'h9;
      4'ha: x1_sbox_r[7:4] = 4'h7;
      4'hb: x1_sbox_r[7:4] = 4'hf;
      4'hc: x1_sbox_r[7:4] = 4'hc;
      4'hd: x1_sbox_r[7:4] = 4'ha;
      4'he: x1_sbox_r[7:4] = 4'h5;
      4'hf: x1_sbox_r[7:4] = 4'he;
    endcase
    case (x1_xor[11:8])
      4'h0: x1_sbox_r[11:8] = 4'h0;
      4'h1: x1_sbox_r[11:8] = 4'h1;
      4'h2: x1_sbox_r[11:8] = 4'h2;
      4'h3: x1_sbox_r[11:8] = 4'h3;
      4'h4: x1_sbox_r[11:8] = 4'h4;
      4'h5: x1_sbox_r[11:8] = 4'h6;
      4'h6: x1_sbox_r[11:8] = 4'h8;
      4'h7: x1_sbox_r[11:8] = 4'hb;
      4'h8: x1_sbox_r[11:8] = 4'hd;
      4'h9: x1_sbox_r[11:8] = 4'h9;
      4'ha: x1_sbox_r[11:8] = 4'h7;
      4'hb: x1_sbox_r[11:8] = 4'hf;
      4'hc: x1_sbox_r[11:8] = 4'hc;
      4'hd: x1_sbox_r[11:8] = 4'ha;
      4'he: x1_sbox_r[11:8] = 4'h5;
      4'hf: x1_sbox_r[11:8] = 4'he;
    endcase
    case (x1_xor[15:12])
      4'h0: x1_sbox_r[15:12] = 4'h0;
      4'h1: x1_sbox_r[15:12] = 4'h1;
      4'h2: x1_sbox_r[15:12] = 4'h2;
      4'h3: x1_sbox_r[15:12] = 4'h3;
      4'h4: x1_sbox_r[15:12] = 4'h4;
      4'h5: x1_sbox_r[15:12] = 4'h6;
      4'h6: x1_sbox_r[15:12] = 4'h8;
      4'h7: x1_sbox_r[15:12] = 4'hb;
      4'h8: x1_sbox_r[15:12] = 4'hd;
      4'h9: x1_sbox_r[15:12] = 4'h9;
      4'ha: x1_sbox_r[15:12] = 4'h7;
      4'hb: x1_sbox_r[15:12] = 4'hf;
      4'hc: x1_sbox_r[15:12] = 4'hc;
      4'hd: x1_sbox_r[15:12] = 4'ha;
      4'he: x1_sbox_r[15:12] = 4'h5;
      4'hf: x1_sbox_r[15:12] = 4'he;
    endcase
    case (x1_xor[19:16])
      4'h0: x1_sbox_r[19:16] = 4'h0;
      4'h1: x1_sbox_r[19:16] = 4'h1;
      4'h2: x1_sbox_r[19:16] = 4'h2;
      4'h3: x1_sbox_r[19:16] = 4'h3;
      4'h4: x1_sbox_r[19:16] = 4'h4;
      4'h5: x1_sbox_r[19:16] = 4'h6;
      4'h6: x1_sbox_r[19:16] = 4'h8;
      4'h7: x1_sbox_r[19:16] = 4'hb;
      4'h8: x1_sbox_r[19:16] = 4'hd;
      4'h9: x1_sbox_r[19:16] = 4'h9;
      4'ha: x1_sbox_r[19:16] = 4'h7;
      4'hb: x1_sbox_r[19:16] = 4'hf;
      4'hc: x1_sbox_r[19:16] = 4'hc;
      4'hd: x1_sbox_r[19:16] = 4'ha;
      4'he: x1_sbox_r[19:16] = 4'h5;
      4'hf: x1_sbox_r[19:16] = 4'he;
    endcase
    case (x1_xor[23:20])
      4'h0: x1_sbox_r[23:20] = 4'h0;
      4'h1: x1_sbox_r[23:20] = 4'h1;
      4'h2: x1_sbox_r[23:20] = 4'h2;
      4'h3: x1_sbox_r[23:20] = 4'h3;
      4'h4: x1_sbox_r[23:20] = 4'h4;
      4'h5: x1_sbox_r[23:20] = 4'h6;
      4'h6: x1_sbox_r[23:20] = 4'h8;
      4'h7: x1_sbox_r[23:20] = 4'hb;
      4'h8: x1_sbox_r[23:20] = 4'hd;
      4'h9: x1_sbox_r[23:20] = 4'h9;
      4'ha: x1_sbox_r[23:20] = 4'h7;
      4'hb: x1_sbox_r[23:20] = 4'hf;
      4'hc: x1_sbox_r[23:20] = 4'hc;
      4'hd: x1_sbox_r[23:20] = 4'ha;
      4'he: x1_sbox_r[23:20] = 4'h5;
      4'hf: x1_sbox_r[23:20] = 4'he;
    endcase
    case (x1_xor[27:24])
      4'h0: x1_sbox_r[27:24] = 4'h0;
      4'h1: x1_sbox_r[27:24] = 4'h1;
      4'h2: x1_sbox_r[27:24] = 4'h2;
      4'h3: x1_sbox_r[27:24] = 4'h3;
      4'h4: x1_sbox_r[27:24] = 4'h4;
      4'h5: x1_sbox_r[27:24] = 4'h6;
      4'h6: x1_sbox_r[27:24] = 4'h8;
      4'h7: x1_sbox_r[27:24] = 4'hb;
      4'h8: x1_sbox_r[27:24] = 4'hd;
      4'h9: x1_sbox_r[27:24] = 4'h9;
      4'ha: x1_sbox_r[27:24] = 4'h7;
      4'hb: x1_sbox_r[27:24] = 4'hf;
      4'hc: x1_sbox_r[27:24] = 4'hc;
      4'hd: x1_sbox_r[27:24] = 4'ha;
      4'he: x1_sbox_r[27:24] = 4'h5;
      4'hf: x1_sbox_r[27:24] = 4'he;
    endcase
    case (x1_xor[31:28])
      4'h0: x1_sbox_r[31:28] = 4'h0;
      4'h1: x1_sbox_r[31:28] = 4'h1;
      4'h2: x1_sbox_r[31:28] = 4'h2;
      4'h3: x1_sbox_r[31:28] = 4'h3;
      4'h4: x1_sbox_r[31:28] = 4'h4;
      4'h5: x1_sbox_r[31:28] = 4'h6;
      4'h6: x1_sbox_r[31:28] = 4'h8;
      4'h7: x1_sbox_r[31:28] = 4'hb;
      4'h8: x1_sbox_r[31:28] = 4'hd;
      4'h9: x1_sbox_r[31:28] = 4'h9;
      4'ha: x1_sbox_r[31:28] = 4'h7;
      4'hb: x1_sbox_r[31:28] = 4'hf;
      4'hc: x1_sbox_r[31:28] = 4'hc;
      4'hd: x1_sbox_r[31:28] = 4'ha;
      4'he: x1_sbox_r[31:28] = 4'h5;
      4'hf: x1_sbox_r[31:28] = 4'he;
    endcase
    case (x1_xor[35:32])
      4'h0: x1_sbox_r[35:32] = 4'h0;
      4'h1: x1_sbox_r[35:32] = 4'h1;
      4'h2: x1_sbox_r[35:32] = 4'h2;
      4'h3: x1_sbox_r[35:32] = 4'h3;
      4'h4: x1_sbox_r[35:32] = 4'h4;
      4'h5: x1_sbox_r[35:32] = 4'h6;
      4'h6: x1_sbox_r[35:32] = 4'h8;
      4'h7: x1_sbox_r[35:32] = 4'hb;
      4'h8: x1_sbox_r[35:32] = 4'hd;
      4'h9: x1_sbox_r[35:32] = 4'h9;
      4'ha: x1_sbox_r[35:32] = 4'h7;
      4'hb: x1_sbox_r[35:32] = 4'hf;
      4'hc: x1_sbox_r[35:32] = 4'hc;
      4'hd: x1_sbox_r[35:32] = 4'ha;
      4'he: x1_sbox_r[35:32] = 4'h5;
      4'hf: x1_sbox_r[35:32] = 4'he;
    endcase
    case (x1_xor[39:36])
      4'h0: x1_sbox_r[39:36] = 4'h0;
      4'h1: x1_sbox_r[39:36] = 4'h1;
      4'h2: x1_sbox_r[39:36] = 4'h2;
      4'h3: x1_sbox_r[39:36] = 4'h3;
      4'h4: x1_sbox_r[39:36] = 4'h4;
      4'h5: x1_sbox_r[39:36] = 4'h6;
      4'h6: x1_sbox_r[39:36] = 4'h8;
      4'h7: x1_sbox_r[39:36] = 4'hb;
      4'h8: x1_sbox_r[39:36] = 4'hd;
      4'h9: x1_sbox_r[39:36] = 4'h9;
      4'ha: x1_sbox_r[39:36] = 4'h7;
      4'hb: x1_sbox_r[39:36] = 4'hf;
      4'hc: x1_sbox_r[39:36] = 4'hc;
      4'hd: x1_sbox_r[39:36] = 4'ha;
      4'he: x1_sbox_r[39:36] = 4'h5;
      4'hf: x1_sbox_r[39:36] = 4'he;
    endcase
    case (x1_xor[43:40])
      4'h0: x1_sbox_r[43:40] = 4'h0;
      4'h1: x1_sbox_r[43:40] = 4'h1;
      4'h2: x1_sbox_r[43:40] = 4'h2;
      4'h3: x1_sbox_r[43:40] = 4'h3;
      4'h4: x1_sbox_r[43:40] = 4'h4;
      4'h5: x1_sbox_r[43:40] = 4'h6;
      4'h6: x1_sbox_r[43:40] = 4'h8;
      4'h7: x1_sbox_r[43:40] = 4'hb;
      4'h8: x1_sbox_r[43:40] = 4'hd;
      4'h9: x1_sbox_r[43:40] = 4'h9;
      4'ha: x1_sbox_r[43:40] = 4'h7;
      4'hb: x1_sbox_r[43:40] = 4'hf;
      4'hc: x1_sbox_r[43:40] = 4'hc;
      4'hd: x1_sbox_r[43:40] = 4'ha;
      4'he: x1_sbox_r[43:40] = 4'h5;
      4'hf: x1_sbox_r[43:40] = 4'he;
    endcase
    case (x1_xor[47:44])
      4'h0: x1_sbox_r[47:44] = 4'h0;
      4'h1: x1_sbox_r[47:44] = 4'h1;
      4'h2: x1_sbox_r[47:44] = 4'h2;
      4'h3: x1_sbox_r[47:44] = 4'h3;
      4'h4: x1_sbox_r[47:44] = 4'h4;
      4'h5: x1_sbox_r[47:44] = 4'h6;
      4'h6: x1_sbox_r[47:44] = 4'h8;
      4'h7: x1_sbox_r[47:44] = 4'hb;
      4'h8: x1_sbox_r[47:44] = 4'hd;
      4'h9: x1_sbox_r[47:44] = 4'h9;
      4'ha: x1_sbox_r[47:44] = 4'h7;
      4'hb: x1_sbox_r[47:44] = 4'hf;
      4'hc: x1_sbox_r[47:44] = 4'hc;
      4'hd: x1_sbox_r[47:44] = 4'ha;
      4'he: x1_sbox_r[47:44] = 4'h5;
      4'hf: x1_sbox_r[47:44] = 4'he;
    endcase
    case (x1_xor[51:48])
      4'h0: x1_sbox_r[51:48] = 4'h0;
      4'h1: x1_sbox_r[51:48] = 4'h1;
      4'h2: x1_sbox_r[51:48] = 4'h2;
      4'h3: x1_sbox_r[51:48] = 4'h3;
      4'h4: x1_sbox_r[51:48] = 4'h4;
      4'h5: x1_sbox_r[51:48] = 4'h6;
      4'h6: x1_sbox_r[51:48] = 4'h8;
      4'h7: x1_sbox_r[51:48] = 4'hb;
      4'h8: x1_sbox_r[51:48] = 4'hd;
      4'h9: x1_sbox_r[51:48] = 4'h9;
      4'ha: x1_sbox_r[51:48] = 4'h7;
      4'hb: x1_sbox_r[51:48] = 4'hf;
      4'hc: x1_sbox_r[51:48] = 4'hc;
      4'hd: x1_sbox_r[51:48] = 4'ha;
      4'he: x1_sbox_r[51:48] = 4'h5;
      4'hf: x1_sbox_r[51:48] = 4'he;
    endcase
    case (x1_xor[55:52])
      4'h0: x1_sbox_r[55:52] = 4'h0;
      4'h1: x1_sbox_r[55:52] = 4'h1;
      4'h2: x1_sbox_r[55:52] = 4'h2;
      4'h3: x1_sbox_r[55:52] = 4'h3;
      4'h4: x1_sbox_r[55:52] = 4'h4;
      4'h5: x1_sbox_r[55:52] = 4'h6;
      4'h6: x1_sbox_r[55:52] = 4'h8;
      4'h7: x1_sbox_r[55:52] = 4'hb;
      4'h8: x1_sbox_r[55:52] = 4'hd;
      4'h9: x1_sbox_r[55:52] = 4'h9;
      4'ha: x1_sbox_r[55:52] = 4'h7;
      4'hb: x1_sbox_r[55:52] = 4'hf;
      4'hc: x1_sbox_r[55:52] = 4'hc;
      4'hd: x1_sbox_r[55:52] = 4'ha;
      4'he: x1_sbox_r[55:52] = 4'h5;
      4'hf: x1_sbox_r[55:52] = 4'he;
    endcase
    case (x1_xor[59:56])
      4'h0: x1_sbox_r[59:56] = 4'h0;
      4'h1: x1_sbox_r[59:56] = 4'h1;
      4'h2: x1_sbox_r[59:56] = 4'h2;
      4'h3: x1_sbox_r[59:56] = 4'h3;
      4'h4: x1_sbox_r[59:56] = 4'h4;
      4'h5: x1_sbox_r[59:56] = 4'h6;
      4'h6: x1_sbox_r[59:56] = 4'h8;
      4'h7: x1_sbox_r[59:56] = 4'hb;
      4'h8: x1_sbox_r[59:56] = 4'hd;
      4'h9: x1_sbox_r[59:56] = 4'h9;
      4'ha: x1_sbox_r[59:56] = 4'h7;
      4'hb: x1_sbox_r[59:56] = 4'hf;
      4'hc: x1_sbox_r[59:56] = 4'hc;
      4'hd: x1_sbox_r[59:56] = 4'ha;
      4'he: x1_sbox_r[59:56] = 4'h5;
      4'hf: x1_sbox_r[59:56] = 4'he;
    endcase
    case (x1_xor[63:60])
      4'h0: x1_sbox_r[63:60] = 4'h0;
      4'h1: x1_sbox_r[63:60] = 4'h1;
      4'h2: x1_sbox_r[63:60] = 4'h2;
      4'h3: x1_sbox_r[63:60] = 4'h3;
      4'h4: x1_sbox_r[63:60] = 4'h4;
      4'h5: x1_sbox_r[63:60] = 4'h6;
      4'h6: x1_sbox_r[63:60] = 4'h8;
      4'h7: x1_sbox_r[63:60] = 4'hb;
      4'h8: x1_sbox_r[63:60] = 4'hd;
      4'h9: x1_sbox_r[63:60] = 4'h9;
      4'ha: x1_sbox_r[63:60] = 4'h7;
      4'hb: x1_sbox_r[63:60] = 4'hf;
      4'hc: x1_sbox_r[63:60] = 4'hc;
      4'hd: x1_sbox_r[63:60] = 4'ha;
      4'he: x1_sbox_r[63:60] = 4'h5;
      4'hf: x1_sbox_r[63:60] = 4'he;
    endcase
  end
  wire [63:0] x1_sbox = x1_sbox_r;

  wire [63:0] x1_pbox;
  assign x1_pbox[1] = x1_sbox[0];
  assign x1_pbox[20] = x1_sbox[1];
  assign x1_pbox[39] = x1_sbox[2];
  assign x1_pbox[58] = x1_sbox[3];
  assign x1_pbox[13] = x1_sbox[4];
  assign x1_pbox[32] = x1_sbox[5];
  assign x1_pbox[51] = x1_sbox[6];
  assign x1_pbox[6] = x1_sbox[7];
  assign x1_pbox[25] = x1_sbox[8];
  assign x1_pbox[44] = x1_sbox[9];
  assign x1_pbox[63] = x1_sbox[10];
  assign x1_pbox[18] = x1_sbox[11];
  assign x1_pbox[37] = x1_sbox[12];
  assign x1_pbox[56] = x1_sbox[13];
  assign x1_pbox[11] = x1_sbox[14];
  assign x1_pbox[30] = x1_sbox[15];
  assign x1_pbox[49] = x1_sbox[16];
  assign x1_pbox[4] = x1_sbox[17];
  assign x1_pbox[23] = x1_sbox[18];
  assign x1_pbox[42] = x1_sbox[19];
  assign x1_pbox[61] = x1_sbox[20];
  assign x1_pbox[16] = x1_sbox[21];
  assign x1_pbox[35] = x1_sbox[22];
  assign x1_pbox[54] = x1_sbox[23];
  assign x1_pbox[9] = x1_sbox[24];
  assign x1_pbox[28] = x1_sbox[25];
  assign x1_pbox[47] = x1_sbox[26];
  assign x1_pbox[2] = x1_sbox[27];
  assign x1_pbox[21] = x1_sbox[28];
  assign x1_pbox[40] = x1_sbox[29];
  assign x1_pbox[59] = x1_sbox[30];
  assign x1_pbox[14] = x1_sbox[31];
  assign x1_pbox[33] = x1_sbox[32];
  assign x1_pbox[52] = x1_sbox[33];
  assign x1_pbox[7] = x1_sbox[34];
  assign x1_pbox[26] = x1_sbox[35];
  assign x1_pbox[45] = x1_sbox[36];
  assign x1_pbox[0] = x1_sbox[37];
  assign x1_pbox[19] = x1_sbox[38];
  assign x1_pbox[38] = x1_sbox[39];
  assign x1_pbox[57] = x1_sbox[40];
  assign x1_pbox[12] = x1_sbox[41];
  assign x1_pbox[31] = x1_sbox[42];
  assign x1_pbox[50] = x1_sbox[43];
  assign x1_pbox[5] = x1_sbox[44];
  assign x1_pbox[24] = x1_sbox[45];
  assign x1_pbox[43] = x1_sbox[46];
  assign x1_pbox[62] = x1_sbox[47];
  assign x1_pbox[17] = x1_sbox[48];
  assign x1_pbox[36] = x1_sbox[49];
  assign x1_pbox[55] = x1_sbox[50];
  assign x1_pbox[10] = x1_sbox[51];
  assign x1_pbox[29] = x1_sbox[52];
  assign x1_pbox[48] = x1_sbox[53];
  assign x1_pbox[3] = x1_sbox[54];
  assign x1_pbox[22] = x1_sbox[55];
  assign x1_pbox[41] = x1_sbox[56];
  assign x1_pbox[60] = x1_sbox[57];
  assign x1_pbox[15] = x1_sbox[58];
  assign x1_pbox[34] = x1_sbox[59];
  assign x1_pbox[53] = x1_sbox[60];
  assign x1_pbox[8] = x1_sbox[61];
  assign x1_pbox[27] = x1_sbox[62];
  assign x1_pbox[46] = x1_sbox[63];

  wire [63:0] x2 = x1_pbox ^ ({x1_pbox[58:0], x1_pbox[63:59]}) ^ ({x1_pbox[54:0], x1_pbox[63:55]});

  // Round 2
  wire [63:0] x2_xor = x2 ^ rk2;

  reg [63:0] x2_sbox_r;
  always @(*) begin
    x2_sbox_r = 64'h0;
    case (x2_xor[3:0])
      4'h0: x2_sbox_r[3:0] = 4'h0;
      4'h1: x2_sbox_r[3:0] = 4'h1;
      4'h2: x2_sbox_r[3:0] = 4'h2;
      4'h3: x2_sbox_r[3:0] = 4'h3;
      4'h4: x2_sbox_r[3:0] = 4'h4;
      4'h5: x2_sbox_r[3:0] = 4'h6;
      4'h6: x2_sbox_r[3:0] = 4'h8;
      4'h7: x2_sbox_r[3:0] = 4'hb;
      4'h8: x2_sbox_r[3:0] = 4'hd;
      4'h9: x2_sbox_r[3:0] = 4'h9;
      4'ha: x2_sbox_r[3:0] = 4'h7;
      4'hb: x2_sbox_r[3:0] = 4'hf;
      4'hc: x2_sbox_r[3:0] = 4'hc;
      4'hd: x2_sbox_r[3:0] = 4'ha;
      4'he: x2_sbox_r[3:0] = 4'h5;
      4'hf: x2_sbox_r[3:0] = 4'he;
    endcase
    case (x2_xor[7:4])
      4'h0: x2_sbox_r[7:4] = 4'h0;
      4'h1: x2_sbox_r[7:4] = 4'h1;
      4'h2: x2_sbox_r[7:4] = 4'h2;
      4'h3: x2_sbox_r[7:4] = 4'h3;
      4'h4: x2_sbox_r[7:4] = 4'h4;
      4'h5: x2_sbox_r[7:4] = 4'h6;
      4'h6: x2_sbox_r[7:4] = 4'h8;
      4'h7: x2_sbox_r[7:4] = 4'hb;
      4'h8: x2_sbox_r[7:4] = 4'hd;
      4'h9: x2_sbox_r[7:4] = 4'h9;
      4'ha: x2_sbox_r[7:4] = 4'h7;
      4'hb: x2_sbox_r[7:4] = 4'hf;
      4'hc: x2_sbox_r[7:4] = 4'hc;
      4'hd: x2_sbox_r[7:4] = 4'ha;
      4'he: x2_sbox_r[7:4] = 4'h5;
      4'hf: x2_sbox_r[7:4] = 4'he;
    endcase
    case (x2_xor[11:8])
      4'h0: x2_sbox_r[11:8] = 4'h0;
      4'h1: x2_sbox_r[11:8] = 4'h1;
      4'h2: x2_sbox_r[11:8] = 4'h2;
      4'h3: x2_sbox_r[11:8] = 4'h3;
      4'h4: x2_sbox_r[11:8] = 4'h4;
      4'h5: x2_sbox_r[11:8] = 4'h6;
      4'h6: x2_sbox_r[11:8] = 4'h8;
      4'h7: x2_sbox_r[11:8] = 4'hb;
      4'h8: x2_sbox_r[11:8] = 4'hd;
      4'h9: x2_sbox_r[11:8] = 4'h9;
      4'ha: x2_sbox_r[11:8] = 4'h7;
      4'hb: x2_sbox_r[11:8] = 4'hf;
      4'hc: x2_sbox_r[11:8] = 4'hc;
      4'hd: x2_sbox_r[11:8] = 4'ha;
      4'he: x2_sbox_r[11:8] = 4'h5;
      4'hf: x2_sbox_r[11:8] = 4'he;
    endcase
    case (x2_xor[15:12])
      4'h0: x2_sbox_r[15:12] = 4'h0;
      4'h1: x2_sbox_r[15:12] = 4'h1;
      4'h2: x2_sbox_r[15:12] = 4'h2;
      4'h3: x2_sbox_r[15:12] = 4'h3;
      4'h4: x2_sbox_r[15:12] = 4'h4;
      4'h5: x2_sbox_r[15:12] = 4'h6;
      4'h6: x2_sbox_r[15:12] = 4'h8;
      4'h7: x2_sbox_r[15:12] = 4'hb;
      4'h8: x2_sbox_r[15:12] = 4'hd;
      4'h9: x2_sbox_r[15:12] = 4'h9;
      4'ha: x2_sbox_r[15:12] = 4'h7;
      4'hb: x2_sbox_r[15:12] = 4'hf;
      4'hc: x2_sbox_r[15:12] = 4'hc;
      4'hd: x2_sbox_r[15:12] = 4'ha;
      4'he: x2_sbox_r[15:12] = 4'h5;
      4'hf: x2_sbox_r[15:12] = 4'he;
    endcase
    case (x2_xor[19:16])
      4'h0: x2_sbox_r[19:16] = 4'h0;
      4'h1: x2_sbox_r[19:16] = 4'h1;
      4'h2: x2_sbox_r[19:16] = 4'h2;
      4'h3: x2_sbox_r[19:16] = 4'h3;
      4'h4: x2_sbox_r[19:16] = 4'h4;
      4'h5: x2_sbox_r[19:16] = 4'h6;
      4'h6: x2_sbox_r[19:16] = 4'h8;
      4'h7: x2_sbox_r[19:16] = 4'hb;
      4'h8: x2_sbox_r[19:16] = 4'hd;
      4'h9: x2_sbox_r[19:16] = 4'h9;
      4'ha: x2_sbox_r[19:16] = 4'h7;
      4'hb: x2_sbox_r[19:16] = 4'hf;
      4'hc: x2_sbox_r[19:16] = 4'hc;
      4'hd: x2_sbox_r[19:16] = 4'ha;
      4'he: x2_sbox_r[19:16] = 4'h5;
      4'hf: x2_sbox_r[19:16] = 4'he;
    endcase
    case (x2_xor[23:20])
      4'h0: x2_sbox_r[23:20] = 4'h0;
      4'h1: x2_sbox_r[23:20] = 4'h1;
      4'h2: x2_sbox_r[23:20] = 4'h2;
      4'h3: x2_sbox_r[23:20] = 4'h3;
      4'h4: x2_sbox_r[23:20] = 4'h4;
      4'h5: x2_sbox_r[23:20] = 4'h6;
      4'h6: x2_sbox_r[23:20] = 4'h8;
      4'h7: x2_sbox_r[23:20] = 4'hb;
      4'h8: x2_sbox_r[23:20] = 4'hd;
      4'h9: x2_sbox_r[23:20] = 4'h9;
      4'ha: x2_sbox_r[23:20] = 4'h7;
      4'hb: x2_sbox_r[23:20] = 4'hf;
      4'hc: x2_sbox_r[23:20] = 4'hc;
      4'hd: x2_sbox_r[23:20] = 4'ha;
      4'he: x2_sbox_r[23:20] = 4'h5;
      4'hf: x2_sbox_r[23:20] = 4'he;
    endcase
    case (x2_xor[27:24])
      4'h0: x2_sbox_r[27:24] = 4'h0;
      4'h1: x2_sbox_r[27:24] = 4'h1;
      4'h2: x2_sbox_r[27:24] = 4'h2;
      4'h3: x2_sbox_r[27:24] = 4'h3;
      4'h4: x2_sbox_r[27:24] = 4'h4;
      4'h5: x2_sbox_r[27:24] = 4'h6;
      4'h6: x2_sbox_r[27:24] = 4'h8;
      4'h7: x2_sbox_r[27:24] = 4'hb;
      4'h8: x2_sbox_r[27:24] = 4'hd;
      4'h9: x2_sbox_r[27:24] = 4'h9;
      4'ha: x2_sbox_r[27:24] = 4'h7;
      4'hb: x2_sbox_r[27:24] = 4'hf;
      4'hc: x2_sbox_r[27:24] = 4'hc;
      4'hd: x2_sbox_r[27:24] = 4'ha;
      4'he: x2_sbox_r[27:24] = 4'h5;
      4'hf: x2_sbox_r[27:24] = 4'he;
    endcase
    case (x2_xor[31:28])
      4'h0: x2_sbox_r[31:28] = 4'h0;
      4'h1: x2_sbox_r[31:28] = 4'h1;
      4'h2: x2_sbox_r[31:28] = 4'h2;
      4'h3: x2_sbox_r[31:28] = 4'h3;
      4'h4: x2_sbox_r[31:28] = 4'h4;
      4'h5: x2_sbox_r[31:28] = 4'h6;
      4'h6: x2_sbox_r[31:28] = 4'h8;
      4'h7: x2_sbox_r[31:28] = 4'hb;
      4'h8: x2_sbox_r[31:28] = 4'hd;
      4'h9: x2_sbox_r[31:28] = 4'h9;
      4'ha: x2_sbox_r[31:28] = 4'h7;
      4'hb: x2_sbox_r[31:28] = 4'hf;
      4'hc: x2_sbox_r[31:28] = 4'hc;
      4'hd: x2_sbox_r[31:28] = 4'ha;
      4'he: x2_sbox_r[31:28] = 4'h5;
      4'hf: x2_sbox_r[31:28] = 4'he;
    endcase
    case (x2_xor[35:32])
      4'h0: x2_sbox_r[35:32] = 4'h0;
      4'h1: x2_sbox_r[35:32] = 4'h1;
      4'h2: x2_sbox_r[35:32] = 4'h2;
      4'h3: x2_sbox_r[35:32] = 4'h3;
      4'h4: x2_sbox_r[35:32] = 4'h4;
      4'h5: x2_sbox_r[35:32] = 4'h6;
      4'h6: x2_sbox_r[35:32] = 4'h8;
      4'h7: x2_sbox_r[35:32] = 4'hb;
      4'h8: x2_sbox_r[35:32] = 4'hd;
      4'h9: x2_sbox_r[35:32] = 4'h9;
      4'ha: x2_sbox_r[35:32] = 4'h7;
      4'hb: x2_sbox_r[35:32] = 4'hf;
      4'hc: x2_sbox_r[35:32] = 4'hc;
      4'hd: x2_sbox_r[35:32] = 4'ha;
      4'he: x2_sbox_r[35:32] = 4'h5;
      4'hf: x2_sbox_r[35:32] = 4'he;
    endcase
    case (x2_xor[39:36])
      4'h0: x2_sbox_r[39:36] = 4'h0;
      4'h1: x2_sbox_r[39:36] = 4'h1;
      4'h2: x2_sbox_r[39:36] = 4'h2;
      4'h3: x2_sbox_r[39:36] = 4'h3;
      4'h4: x2_sbox_r[39:36] = 4'h4;
      4'h5: x2_sbox_r[39:36] = 4'h6;
      4'h6: x2_sbox_r[39:36] = 4'h8;
      4'h7: x2_sbox_r[39:36] = 4'hb;
      4'h8: x2_sbox_r[39:36] = 4'hd;
      4'h9: x2_sbox_r[39:36] = 4'h9;
      4'ha: x2_sbox_r[39:36] = 4'h7;
      4'hb: x2_sbox_r[39:36] = 4'hf;
      4'hc: x2_sbox_r[39:36] = 4'hc;
      4'hd: x2_sbox_r[39:36] = 4'ha;
      4'he: x2_sbox_r[39:36] = 4'h5;
      4'hf: x2_sbox_r[39:36] = 4'he;
    endcase
    case (x2_xor[43:40])
      4'h0: x2_sbox_r[43:40] = 4'h0;
      4'h1: x2_sbox_r[43:40] = 4'h1;
      4'h2: x2_sbox_r[43:40] = 4'h2;
      4'h3: x2_sbox_r[43:40] = 4'h3;
      4'h4: x2_sbox_r[43:40] = 4'h4;
      4'h5: x2_sbox_r[43:40] = 4'h6;
      4'h6: x2_sbox_r[43:40] = 4'h8;
      4'h7: x2_sbox_r[43:40] = 4'hb;
      4'h8: x2_sbox_r[43:40] = 4'hd;
      4'h9: x2_sbox_r[43:40] = 4'h9;
      4'ha: x2_sbox_r[43:40] = 4'h7;
      4'hb: x2_sbox_r[43:40] = 4'hf;
      4'hc: x2_sbox_r[43:40] = 4'hc;
      4'hd: x2_sbox_r[43:40] = 4'ha;
      4'he: x2_sbox_r[43:40] = 4'h5;
      4'hf: x2_sbox_r[43:40] = 4'he;
    endcase
    case (x2_xor[47:44])
      4'h0: x2_sbox_r[47:44] = 4'h0;
      4'h1: x2_sbox_r[47:44] = 4'h1;
      4'h2: x2_sbox_r[47:44] = 4'h2;
      4'h3: x2_sbox_r[47:44] = 4'h3;
      4'h4: x2_sbox_r[47:44] = 4'h4;
      4'h5: x2_sbox_r[47:44] = 4'h6;
      4'h6: x2_sbox_r[47:44] = 4'h8;
      4'h7: x2_sbox_r[47:44] = 4'hb;
      4'h8: x2_sbox_r[47:44] = 4'hd;
      4'h9: x2_sbox_r[47:44] = 4'h9;
      4'ha: x2_sbox_r[47:44] = 4'h7;
      4'hb: x2_sbox_r[47:44] = 4'hf;
      4'hc: x2_sbox_r[47:44] = 4'hc;
      4'hd: x2_sbox_r[47:44] = 4'ha;
      4'he: x2_sbox_r[47:44] = 4'h5;
      4'hf: x2_sbox_r[47:44] = 4'he;
    endcase
    case (x2_xor[51:48])
      4'h0: x2_sbox_r[51:48] = 4'h0;
      4'h1: x2_sbox_r[51:48] = 4'h1;
      4'h2: x2_sbox_r[51:48] = 4'h2;
      4'h3: x2_sbox_r[51:48] = 4'h3;
      4'h4: x2_sbox_r[51:48] = 4'h4;
      4'h5: x2_sbox_r[51:48] = 4'h6;
      4'h6: x2_sbox_r[51:48] = 4'h8;
      4'h7: x2_sbox_r[51:48] = 4'hb;
      4'h8: x2_sbox_r[51:48] = 4'hd;
      4'h9: x2_sbox_r[51:48] = 4'h9;
      4'ha: x2_sbox_r[51:48] = 4'h7;
      4'hb: x2_sbox_r[51:48] = 4'hf;
      4'hc: x2_sbox_r[51:48] = 4'hc;
      4'hd: x2_sbox_r[51:48] = 4'ha;
      4'he: x2_sbox_r[51:48] = 4'h5;
      4'hf: x2_sbox_r[51:48] = 4'he;
    endcase
    case (x2_xor[55:52])
      4'h0: x2_sbox_r[55:52] = 4'h0;
      4'h1: x2_sbox_r[55:52] = 4'h1;
      4'h2: x2_sbox_r[55:52] = 4'h2;
      4'h3: x2_sbox_r[55:52] = 4'h3;
      4'h4: x2_sbox_r[55:52] = 4'h4;
      4'h5: x2_sbox_r[55:52] = 4'h6;
      4'h6: x2_sbox_r[55:52] = 4'h8;
      4'h7: x2_sbox_r[55:52] = 4'hb;
      4'h8: x2_sbox_r[55:52] = 4'hd;
      4'h9: x2_sbox_r[55:52] = 4'h9;
      4'ha: x2_sbox_r[55:52] = 4'h7;
      4'hb: x2_sbox_r[55:52] = 4'hf;
      4'hc: x2_sbox_r[55:52] = 4'hc;
      4'hd: x2_sbox_r[55:52] = 4'ha;
      4'he: x2_sbox_r[55:52] = 4'h5;
      4'hf: x2_sbox_r[55:52] = 4'he;
    endcase
    case (x2_xor[59:56])
      4'h0: x2_sbox_r[59:56] = 4'h0;
      4'h1: x2_sbox_r[59:56] = 4'h1;
      4'h2: x2_sbox_r[59:56] = 4'h2;
      4'h3: x2_sbox_r[59:56] = 4'h3;
      4'h4: x2_sbox_r[59:56] = 4'h4;
      4'h5: x2_sbox_r[59:56] = 4'h6;
      4'h6: x2_sbox_r[59:56] = 4'h8;
      4'h7: x2_sbox_r[59:56] = 4'hb;
      4'h8: x2_sbox_r[59:56] = 4'hd;
      4'h9: x2_sbox_r[59:56] = 4'h9;
      4'ha: x2_sbox_r[59:56] = 4'h7;
      4'hb: x2_sbox_r[59:56] = 4'hf;
      4'hc: x2_sbox_r[59:56] = 4'hc;
      4'hd: x2_sbox_r[59:56] = 4'ha;
      4'he: x2_sbox_r[59:56] = 4'h5;
      4'hf: x2_sbox_r[59:56] = 4'he;
    endcase
    case (x2_xor[63:60])
      4'h0: x2_sbox_r[63:60] = 4'h0;
      4'h1: x2_sbox_r[63:60] = 4'h1;
      4'h2: x2_sbox_r[63:60] = 4'h2;
      4'h3: x2_sbox_r[63:60] = 4'h3;
      4'h4: x2_sbox_r[63:60] = 4'h4;
      4'h5: x2_sbox_r[63:60] = 4'h6;
      4'h6: x2_sbox_r[63:60] = 4'h8;
      4'h7: x2_sbox_r[63:60] = 4'hb;
      4'h8: x2_sbox_r[63:60] = 4'hd;
      4'h9: x2_sbox_r[63:60] = 4'h9;
      4'ha: x2_sbox_r[63:60] = 4'h7;
      4'hb: x2_sbox_r[63:60] = 4'hf;
      4'hc: x2_sbox_r[63:60] = 4'hc;
      4'hd: x2_sbox_r[63:60] = 4'ha;
      4'he: x2_sbox_r[63:60] = 4'h5;
      4'hf: x2_sbox_r[63:60] = 4'he;
    endcase
  end
  wire [63:0] x2_sbox = x2_sbox_r;

  wire [63:0] x2_pbox;
  assign x2_pbox[1] = x2_sbox[0];
  assign x2_pbox[20] = x2_sbox[1];
  assign x2_pbox[39] = x2_sbox[2];
  assign x2_pbox[58] = x2_sbox[3];
  assign x2_pbox[13] = x2_sbox[4];
  assign x2_pbox[32] = x2_sbox[5];
  assign x2_pbox[51] = x2_sbox[6];
  assign x2_pbox[6] = x2_sbox[7];
  assign x2_pbox[25] = x2_sbox[8];
  assign x2_pbox[44] = x2_sbox[9];
  assign x2_pbox[63] = x2_sbox[10];
  assign x2_pbox[18] = x2_sbox[11];
  assign x2_pbox[37] = x2_sbox[12];
  assign x2_pbox[56] = x2_sbox[13];
  assign x2_pbox[11] = x2_sbox[14];
  assign x2_pbox[30] = x2_sbox[15];
  assign x2_pbox[49] = x2_sbox[16];
  assign x2_pbox[4] = x2_sbox[17];
  assign x2_pbox[23] = x2_sbox[18];
  assign x2_pbox[42] = x2_sbox[19];
  assign x2_pbox[61] = x2_sbox[20];
  assign x2_pbox[16] = x2_sbox[21];
  assign x2_pbox[35] = x2_sbox[22];
  assign x2_pbox[54] = x2_sbox[23];
  assign x2_pbox[9] = x2_sbox[24];
  assign x2_pbox[28] = x2_sbox[25];
  assign x2_pbox[47] = x2_sbox[26];
  assign x2_pbox[2] = x2_sbox[27];
  assign x2_pbox[21] = x2_sbox[28];
  assign x2_pbox[40] = x2_sbox[29];
  assign x2_pbox[59] = x2_sbox[30];
  assign x2_pbox[14] = x2_sbox[31];
  assign x2_pbox[33] = x2_sbox[32];
  assign x2_pbox[52] = x2_sbox[33];
  assign x2_pbox[7] = x2_sbox[34];
  assign x2_pbox[26] = x2_sbox[35];
  assign x2_pbox[45] = x2_sbox[36];
  assign x2_pbox[0] = x2_sbox[37];
  assign x2_pbox[19] = x2_sbox[38];
  assign x2_pbox[38] = x2_sbox[39];
  assign x2_pbox[57] = x2_sbox[40];
  assign x2_pbox[12] = x2_sbox[41];
  assign x2_pbox[31] = x2_sbox[42];
  assign x2_pbox[50] = x2_sbox[43];
  assign x2_pbox[5] = x2_sbox[44];
  assign x2_pbox[24] = x2_sbox[45];
  assign x2_pbox[43] = x2_sbox[46];
  assign x2_pbox[62] = x2_sbox[47];
  assign x2_pbox[17] = x2_sbox[48];
  assign x2_pbox[36] = x2_sbox[49];
  assign x2_pbox[55] = x2_sbox[50];
  assign x2_pbox[10] = x2_sbox[51];
  assign x2_pbox[29] = x2_sbox[52];
  assign x2_pbox[48] = x2_sbox[53];
  assign x2_pbox[3] = x2_sbox[54];
  assign x2_pbox[22] = x2_sbox[55];
  assign x2_pbox[41] = x2_sbox[56];
  assign x2_pbox[60] = x2_sbox[57];
  assign x2_pbox[15] = x2_sbox[58];
  assign x2_pbox[34] = x2_sbox[59];
  assign x2_pbox[53] = x2_sbox[60];
  assign x2_pbox[8] = x2_sbox[61];
  assign x2_pbox[27] = x2_sbox[62];
  assign x2_pbox[46] = x2_sbox[63];

  wire [63:0] x3 = x2_pbox ^ ({x2_pbox[58:0], x2_pbox[63:59]}) ^ ({x2_pbox[54:0], x2_pbox[63:55]});

  // Round 3
  wire [63:0] x3_xor = x3 ^ rk3;

  reg [63:0] x3_sbox_r;
  always @(*) begin
    x3_sbox_r = 64'h0;
    case (x3_xor[3:0])
      4'h0: x3_sbox_r[3:0] = 4'h0;
      4'h1: x3_sbox_r[3:0] = 4'h1;
      4'h2: x3_sbox_r[3:0] = 4'h2;
      4'h3: x3_sbox_r[3:0] = 4'h3;
      4'h4: x3_sbox_r[3:0] = 4'h4;
      4'h5: x3_sbox_r[3:0] = 4'h6;
      4'h6: x3_sbox_r[3:0] = 4'h8;
      4'h7: x3_sbox_r[3:0] = 4'hb;
      4'h8: x3_sbox_r[3:0] = 4'hd;
      4'h9: x3_sbox_r[3:0] = 4'h9;
      4'ha: x3_sbox_r[3:0] = 4'h7;
      4'hb: x3_sbox_r[3:0] = 4'hf;
      4'hc: x3_sbox_r[3:0] = 4'hc;
      4'hd: x3_sbox_r[3:0] = 4'ha;
      4'he: x3_sbox_r[3:0] = 4'h5;
      4'hf: x3_sbox_r[3:0] = 4'he;
    endcase
    case (x3_xor[7:4])
      4'h0: x3_sbox_r[7:4] = 4'h0;
      4'h1: x3_sbox_r[7:4] = 4'h1;
      4'h2: x3_sbox_r[7:4] = 4'h2;
      4'h3: x3_sbox_r[7:4] = 4'h3;
      4'h4: x3_sbox_r[7:4] = 4'h4;
      4'h5: x3_sbox_r[7:4] = 4'h6;
      4'h6: x3_sbox_r[7:4] = 4'h8;
      4'h7: x3_sbox_r[7:4] = 4'hb;
      4'h8: x3_sbox_r[7:4] = 4'hd;
      4'h9: x3_sbox_r[7:4] = 4'h9;
      4'ha: x3_sbox_r[7:4] = 4'h7;
      4'hb: x3_sbox_r[7:4] = 4'hf;
      4'hc: x3_sbox_r[7:4] = 4'hc;
      4'hd: x3_sbox_r[7:4] = 4'ha;
      4'he: x3_sbox_r[7:4] = 4'h5;
      4'hf: x3_sbox_r[7:4] = 4'he;
    endcase
    case (x3_xor[11:8])
      4'h0: x3_sbox_r[11:8] = 4'h0;
      4'h1: x3_sbox_r[11:8] = 4'h1;
      4'h2: x3_sbox_r[11:8] = 4'h2;
      4'h3: x3_sbox_r[11:8] = 4'h3;
      4'h4: x3_sbox_r[11:8] = 4'h4;
      4'h5: x3_sbox_r[11:8] = 4'h6;
      4'h6: x3_sbox_r[11:8] = 4'h8;
      4'h7: x3_sbox_r[11:8] = 4'hb;
      4'h8: x3_sbox_r[11:8] = 4'hd;
      4'h9: x3_sbox_r[11:8] = 4'h9;
      4'ha: x3_sbox_r[11:8] = 4'h7;
      4'hb: x3_sbox_r[11:8] = 4'hf;
      4'hc: x3_sbox_r[11:8] = 4'hc;
      4'hd: x3_sbox_r[11:8] = 4'ha;
      4'he: x3_sbox_r[11:8] = 4'h5;
      4'hf: x3_sbox_r[11:8] = 4'he;
    endcase
    case (x3_xor[15:12])
      4'h0: x3_sbox_r[15:12] = 4'h0;
      4'h1: x3_sbox_r[15:12] = 4'h1;
      4'h2: x3_sbox_r[15:12] = 4'h2;
      4'h3: x3_sbox_r[15:12] = 4'h3;
      4'h4: x3_sbox_r[15:12] = 4'h4;
      4'h5: x3_sbox_r[15:12] = 4'h6;
      4'h6: x3_sbox_r[15:12] = 4'h8;
      4'h7: x3_sbox_r[15:12] = 4'hb;
      4'h8: x3_sbox_r[15:12] = 4'hd;
      4'h9: x3_sbox_r[15:12] = 4'h9;
      4'ha: x3_sbox_r[15:12] = 4'h7;
      4'hb: x3_sbox_r[15:12] = 4'hf;
      4'hc: x3_sbox_r[15:12] = 4'hc;
      4'hd: x3_sbox_r[15:12] = 4'ha;
      4'he: x3_sbox_r[15:12] = 4'h5;
      4'hf: x3_sbox_r[15:12] = 4'he;
    endcase
    case (x3_xor[19:16])
      4'h0: x3_sbox_r[19:16] = 4'h0;
      4'h1: x3_sbox_r[19:16] = 4'h1;
      4'h2: x3_sbox_r[19:16] = 4'h2;
      4'h3: x3_sbox_r[19:16] = 4'h3;
      4'h4: x3_sbox_r[19:16] = 4'h4;
      4'h5: x3_sbox_r[19:16] = 4'h6;
      4'h6: x3_sbox_r[19:16] = 4'h8;
      4'h7: x3_sbox_r[19:16] = 4'hb;
      4'h8: x3_sbox_r[19:16] = 4'hd;
      4'h9: x3_sbox_r[19:16] = 4'h9;
      4'ha: x3_sbox_r[19:16] = 4'h7;
      4'hb: x3_sbox_r[19:16] = 4'hf;
      4'hc: x3_sbox_r[19:16] = 4'hc;
      4'hd: x3_sbox_r[19:16] = 4'ha;
      4'he: x3_sbox_r[19:16] = 4'h5;
      4'hf: x3_sbox_r[19:16] = 4'he;
    endcase
    case (x3_xor[23:20])
      4'h0: x3_sbox_r[23:20] = 4'h0;
      4'h1: x3_sbox_r[23:20] = 4'h1;
      4'h2: x3_sbox_r[23:20] = 4'h2;
      4'h3: x3_sbox_r[23:20] = 4'h3;
      4'h4: x3_sbox_r[23:20] = 4'h4;
      4'h5: x3_sbox_r[23:20] = 4'h6;
      4'h6: x3_sbox_r[23:20] = 4'h8;
      4'h7: x3_sbox_r[23:20] = 4'hb;
      4'h8: x3_sbox_r[23:20] = 4'hd;
      4'h9: x3_sbox_r[23:20] = 4'h9;
      4'ha: x3_sbox_r[23:20] = 4'h7;
      4'hb: x3_sbox_r[23:20] = 4'hf;
      4'hc: x3_sbox_r[23:20] = 4'hc;
      4'hd: x3_sbox_r[23:20] = 4'ha;
      4'he: x3_sbox_r[23:20] = 4'h5;
      4'hf: x3_sbox_r[23:20] = 4'he;
    endcase
    case (x3_xor[27:24])
      4'h0: x3_sbox_r[27:24] = 4'h0;
      4'h1: x3_sbox_r[27:24] = 4'h1;
      4'h2: x3_sbox_r[27:24] = 4'h2;
      4'h3: x3_sbox_r[27:24] = 4'h3;
      4'h4: x3_sbox_r[27:24] = 4'h4;
      4'h5: x3_sbox_r[27:24] = 4'h6;
      4'h6: x3_sbox_r[27:24] = 4'h8;
      4'h7: x3_sbox_r[27:24] = 4'hb;
      4'h8: x3_sbox_r[27:24] = 4'hd;
      4'h9: x3_sbox_r[27:24] = 4'h9;
      4'ha: x3_sbox_r[27:24] = 4'h7;
      4'hb: x3_sbox_r[27:24] = 4'hf;
      4'hc: x3_sbox_r[27:24] = 4'hc;
      4'hd: x3_sbox_r[27:24] = 4'ha;
      4'he: x3_sbox_r[27:24] = 4'h5;
      4'hf: x3_sbox_r[27:24] = 4'he;
    endcase
    case (x3_xor[31:28])
      4'h0: x3_sbox_r[31:28] = 4'h0;
      4'h1: x3_sbox_r[31:28] = 4'h1;
      4'h2: x3_sbox_r[31:28] = 4'h2;
      4'h3: x3_sbox_r[31:28] = 4'h3;
      4'h4: x3_sbox_r[31:28] = 4'h4;
      4'h5: x3_sbox_r[31:28] = 4'h6;
      4'h6: x3_sbox_r[31:28] = 4'h8;
      4'h7: x3_sbox_r[31:28] = 4'hb;
      4'h8: x3_sbox_r[31:28] = 4'hd;
      4'h9: x3_sbox_r[31:28] = 4'h9;
      4'ha: x3_sbox_r[31:28] = 4'h7;
      4'hb: x3_sbox_r[31:28] = 4'hf;
      4'hc: x3_sbox_r[31:28] = 4'hc;
      4'hd: x3_sbox_r[31:28] = 4'ha;
      4'he: x3_sbox_r[31:28] = 4'h5;
      4'hf: x3_sbox_r[31:28] = 4'he;
    endcase
    case (x3_xor[35:32])
      4'h0: x3_sbox_r[35:32] = 4'h0;
      4'h1: x3_sbox_r[35:32] = 4'h1;
      4'h2: x3_sbox_r[35:32] = 4'h2;
      4'h3: x3_sbox_r[35:32] = 4'h3;
      4'h4: x3_sbox_r[35:32] = 4'h4;
      4'h5: x3_sbox_r[35:32] = 4'h6;
      4'h6: x3_sbox_r[35:32] = 4'h8;
      4'h7: x3_sbox_r[35:32] = 4'hb;
      4'h8: x3_sbox_r[35:32] = 4'hd;
      4'h9: x3_sbox_r[35:32] = 4'h9;
      4'ha: x3_sbox_r[35:32] = 4'h7;
      4'hb: x3_sbox_r[35:32] = 4'hf;
      4'hc: x3_sbox_r[35:32] = 4'hc;
      4'hd: x3_sbox_r[35:32] = 4'ha;
      4'he: x3_sbox_r[35:32] = 4'h5;
      4'hf: x3_sbox_r[35:32] = 4'he;
    endcase
    case (x3_xor[39:36])
      4'h0: x3_sbox_r[39:36] = 4'h0;
      4'h1: x3_sbox_r[39:36] = 4'h1;
      4'h2: x3_sbox_r[39:36] = 4'h2;
      4'h3: x3_sbox_r[39:36] = 4'h3;
      4'h4: x3_sbox_r[39:36] = 4'h4;
      4'h5: x3_sbox_r[39:36] = 4'h6;
      4'h6: x3_sbox_r[39:36] = 4'h8;
      4'h7: x3_sbox_r[39:36] = 4'hb;
      4'h8: x3_sbox_r[39:36] = 4'hd;
      4'h9: x3_sbox_r[39:36] = 4'h9;
      4'ha: x3_sbox_r[39:36] = 4'h7;
      4'hb: x3_sbox_r[39:36] = 4'hf;
      4'hc: x3_sbox_r[39:36] = 4'hc;
      4'hd: x3_sbox_r[39:36] = 4'ha;
      4'he: x3_sbox_r[39:36] = 4'h5;
      4'hf: x3_sbox_r[39:36] = 4'he;
    endcase
    case (x3_xor[43:40])
      4'h0: x3_sbox_r[43:40] = 4'h0;
      4'h1: x3_sbox_r[43:40] = 4'h1;
      4'h2: x3_sbox_r[43:40] = 4'h2;
      4'h3: x3_sbox_r[43:40] = 4'h3;
      4'h4: x3_sbox_r[43:40] = 4'h4;
      4'h5: x3_sbox_r[43:40] = 4'h6;
      4'h6: x3_sbox_r[43:40] = 4'h8;
      4'h7: x3_sbox_r[43:40] = 4'hb;
      4'h8: x3_sbox_r[43:40] = 4'hd;
      4'h9: x3_sbox_r[43:40] = 4'h9;
      4'ha: x3_sbox_r[43:40] = 4'h7;
      4'hb: x3_sbox_r[43:40] = 4'hf;
      4'hc: x3_sbox_r[43:40] = 4'hc;
      4'hd: x3_sbox_r[43:40] = 4'ha;
      4'he: x3_sbox_r[43:40] = 4'h5;
      4'hf: x3_sbox_r[43:40] = 4'he;
    endcase
    case (x3_xor[47:44])
      4'h0: x3_sbox_r[47:44] = 4'h0;
      4'h1: x3_sbox_r[47:44] = 4'h1;
      4'h2: x3_sbox_r[47:44] = 4'h2;
      4'h3: x3_sbox_r[47:44] = 4'h3;
      4'h4: x3_sbox_r[47:44] = 4'h4;
      4'h5: x3_sbox_r[47:44] = 4'h6;
      4'h6: x3_sbox_r[47:44] = 4'h8;
      4'h7: x3_sbox_r[47:44] = 4'hb;
      4'h8: x3_sbox_r[47:44] = 4'hd;
      4'h9: x3_sbox_r[47:44] = 4'h9;
      4'ha: x3_sbox_r[47:44] = 4'h7;
      4'hb: x3_sbox_r[47:44] = 4'hf;
      4'hc: x3_sbox_r[47:44] = 4'hc;
      4'hd: x3_sbox_r[47:44] = 4'ha;
      4'he: x3_sbox_r[47:44] = 4'h5;
      4'hf: x3_sbox_r[47:44] = 4'he;
    endcase
    case (x3_xor[51:48])
      4'h0: x3_sbox_r[51:48] = 4'h0;
      4'h1: x3_sbox_r[51:48] = 4'h1;
      4'h2: x3_sbox_r[51:48] = 4'h2;
      4'h3: x3_sbox_r[51:48] = 4'h3;
      4'h4: x3_sbox_r[51:48] = 4'h4;
      4'h5: x3_sbox_r[51:48] = 4'h6;
      4'h6: x3_sbox_r[51:48] = 4'h8;
      4'h7: x3_sbox_r[51:48] = 4'hb;
      4'h8: x3_sbox_r[51:48] = 4'hd;
      4'h9: x3_sbox_r[51:48] = 4'h9;
      4'ha: x3_sbox_r[51:48] = 4'h7;
      4'hb: x3_sbox_r[51:48] = 4'hf;
      4'hc: x3_sbox_r[51:48] = 4'hc;
      4'hd: x3_sbox_r[51:48] = 4'ha;
      4'he: x3_sbox_r[51:48] = 4'h5;
      4'hf: x3_sbox_r[51:48] = 4'he;
    endcase
    case (x3_xor[55:52])
      4'h0: x3_sbox_r[55:52] = 4'h0;
      4'h1: x3_sbox_r[55:52] = 4'h1;
      4'h2: x3_sbox_r[55:52] = 4'h2;
      4'h3: x3_sbox_r[55:52] = 4'h3;
      4'h4: x3_sbox_r[55:52] = 4'h4;
      4'h5: x3_sbox_r[55:52] = 4'h6;
      4'h6: x3_sbox_r[55:52] = 4'h8;
      4'h7: x3_sbox_r[55:52] = 4'hb;
      4'h8: x3_sbox_r[55:52] = 4'hd;
      4'h9: x3_sbox_r[55:52] = 4'h9;
      4'ha: x3_sbox_r[55:52] = 4'h7;
      4'hb: x3_sbox_r[55:52] = 4'hf;
      4'hc: x3_sbox_r[55:52] = 4'hc;
      4'hd: x3_sbox_r[55:52] = 4'ha;
      4'he: x3_sbox_r[55:52] = 4'h5;
      4'hf: x3_sbox_r[55:52] = 4'he;
    endcase
    case (x3_xor[59:56])
      4'h0: x3_sbox_r[59:56] = 4'h0;
      4'h1: x3_sbox_r[59:56] = 4'h1;
      4'h2: x3_sbox_r[59:56] = 4'h2;
      4'h3: x3_sbox_r[59:56] = 4'h3;
      4'h4: x3_sbox_r[59:56] = 4'h4;
      4'h5: x3_sbox_r[59:56] = 4'h6;
      4'h6: x3_sbox_r[59:56] = 4'h8;
      4'h7: x3_sbox_r[59:56] = 4'hb;
      4'h8: x3_sbox_r[59:56] = 4'hd;
      4'h9: x3_sbox_r[59:56] = 4'h9;
      4'ha: x3_sbox_r[59:56] = 4'h7;
      4'hb: x3_sbox_r[59:56] = 4'hf;
      4'hc: x3_sbox_r[59:56] = 4'hc;
      4'hd: x3_sbox_r[59:56] = 4'ha;
      4'he: x3_sbox_r[59:56] = 4'h5;
      4'hf: x3_sbox_r[59:56] = 4'he;
    endcase
    case (x3_xor[63:60])
      4'h0: x3_sbox_r[63:60] = 4'h0;
      4'h1: x3_sbox_r[63:60] = 4'h1;
      4'h2: x3_sbox_r[63:60] = 4'h2;
      4'h3: x3_sbox_r[63:60] = 4'h3;
      4'h4: x3_sbox_r[63:60] = 4'h4;
      4'h5: x3_sbox_r[63:60] = 4'h6;
      4'h6: x3_sbox_r[63:60] = 4'h8;
      4'h7: x3_sbox_r[63:60] = 4'hb;
      4'h8: x3_sbox_r[63:60] = 4'hd;
      4'h9: x3_sbox_r[63:60] = 4'h9;
      4'ha: x3_sbox_r[63:60] = 4'h7;
      4'hb: x3_sbox_r[63:60] = 4'hf;
      4'hc: x3_sbox_r[63:60] = 4'hc;
      4'hd: x3_sbox_r[63:60] = 4'ha;
      4'he: x3_sbox_r[63:60] = 4'h5;
      4'hf: x3_sbox_r[63:60] = 4'he;
    endcase
  end
  wire [63:0] x3_sbox = x3_sbox_r;

  wire [63:0] x3_pbox;
  assign x3_pbox[1] = x3_sbox[0];
  assign x3_pbox[20] = x3_sbox[1];
  assign x3_pbox[39] = x3_sbox[2];
  assign x3_pbox[58] = x3_sbox[3];
  assign x3_pbox[13] = x3_sbox[4];
  assign x3_pbox[32] = x3_sbox[5];
  assign x3_pbox[51] = x3_sbox[6];
  assign x3_pbox[6] = x3_sbox[7];
  assign x3_pbox[25] = x3_sbox[8];
  assign x3_pbox[44] = x3_sbox[9];
  assign x3_pbox[63] = x3_sbox[10];
  assign x3_pbox[18] = x3_sbox[11];
  assign x3_pbox[37] = x3_sbox[12];
  assign x3_pbox[56] = x3_sbox[13];
  assign x3_pbox[11] = x3_sbox[14];
  assign x3_pbox[30] = x3_sbox[15];
  assign x3_pbox[49] = x3_sbox[16];
  assign x3_pbox[4] = x3_sbox[17];
  assign x3_pbox[23] = x3_sbox[18];
  assign x3_pbox[42] = x3_sbox[19];
  assign x3_pbox[61] = x3_sbox[20];
  assign x3_pbox[16] = x3_sbox[21];
  assign x3_pbox[35] = x3_sbox[22];
  assign x3_pbox[54] = x3_sbox[23];
  assign x3_pbox[9] = x3_sbox[24];
  assign x3_pbox[28] = x3_sbox[25];
  assign x3_pbox[47] = x3_sbox[26];
  assign x3_pbox[2] = x3_sbox[27];
  assign x3_pbox[21] = x3_sbox[28];
  assign x3_pbox[40] = x3_sbox[29];
  assign x3_pbox[59] = x3_sbox[30];
  assign x3_pbox[14] = x3_sbox[31];
  assign x3_pbox[33] = x3_sbox[32];
  assign x3_pbox[52] = x3_sbox[33];
  assign x3_pbox[7] = x3_sbox[34];
  assign x3_pbox[26] = x3_sbox[35];
  assign x3_pbox[45] = x3_sbox[36];
  assign x3_pbox[0] = x3_sbox[37];
  assign x3_pbox[19] = x3_sbox[38];
  assign x3_pbox[38] = x3_sbox[39];
  assign x3_pbox[57] = x3_sbox[40];
  assign x3_pbox[12] = x3_sbox[41];
  assign x3_pbox[31] = x3_sbox[42];
  assign x3_pbox[50] = x3_sbox[43];
  assign x3_pbox[5] = x3_sbox[44];
  assign x3_pbox[24] = x3_sbox[45];
  assign x3_pbox[43] = x3_sbox[46];
  assign x3_pbox[62] = x3_sbox[47];
  assign x3_pbox[17] = x3_sbox[48];
  assign x3_pbox[36] = x3_sbox[49];
  assign x3_pbox[55] = x3_sbox[50];
  assign x3_pbox[10] = x3_sbox[51];
  assign x3_pbox[29] = x3_sbox[52];
  assign x3_pbox[48] = x3_sbox[53];
  assign x3_pbox[3] = x3_sbox[54];
  assign x3_pbox[22] = x3_sbox[55];
  assign x3_pbox[41] = x3_sbox[56];
  assign x3_pbox[60] = x3_sbox[57];
  assign x3_pbox[15] = x3_sbox[58];
  assign x3_pbox[34] = x3_sbox[59];
  assign x3_pbox[53] = x3_sbox[60];
  assign x3_pbox[8] = x3_sbox[61];
  assign x3_pbox[27] = x3_sbox[62];
  assign x3_pbox[46] = x3_sbox[63];

  wire [63:0] out_internal = x3_pbox ^ ({x3_pbox[58:0], x3_pbox[63:59]}) ^ ({x3_pbox[54:0], x3_pbox[63:55]});

  assign out = out_internal;

endmodule