// al_dualand5a: Wave-10: 5-stage dual-AND on and6a triplets, preview 2nd pair (floor attack) (generated by gen_wave1.py)
module al_dualand5a(
    input [63:0] val,
    input [63:0] key,
    output [63:0] out
);
    wire [63:0] x0 = val ^ key;
    wire [63:0] s0a = {x0[62:0], x0[63:63]};
    wire [63:0] s0b = {x0[61:0], x0[63:62]};
    wire [63:0] s0c = {x0[56:0], x0[63:57]};
    wire [63:0] s0d = {x0[44:0], x0[63:45]};
    wire [63:0] s0e = {x0[50:0], x0[63:51]};
    wire [63:0] x1 = x0 ^ (s0a & s0b) ^ (s0c & s0d) ^ s0e;
    wire [63:0] s1a = {x1[56:0], x1[63:57]};
    wire [63:0] s1b = {x1[44:0], x1[63:45]};
    wire [63:0] s1c = {x1[60:0], x1[63:61]};
    wire [63:0] s1d = {x1[52:0], x1[63:53]};
    wire [63:0] s1e = {x1[58:0], x1[63:59]};
    wire [63:0] x2 = x1 ^ (s1a & s1b) ^ (s1c & s1d) ^ s1e;
    wire [63:0] s2a = {x2[60:0], x2[63:61]};
    wire [63:0] s2b = {x2[52:0], x2[63:53]};
    wire [63:0] s2c = {x2[46:0], x2[63:47]};
    wire [63:0] s2d = {x2[32:0], x2[63:33]};
    wire [63:0] s2e = {x2[34:0], x2[63:35]};
    wire [63:0] x3 = x2 ^ (s2a & s2b) ^ (s2c & s2d) ^ s2e;
    wire [63:0] s3a = {x3[46:0], x3[63:47]};
    wire [63:0] s3b = {x3[32:0], x3[63:33]};
    wire [63:0] s3c = {x3[52:0], x3[63:53]};
    wire [63:0] s3d = {x3[40:0], x3[63:41]};
    wire [63:0] s3e = {x3[56:0], x3[63:57]};
    wire [63:0] x4 = x3 ^ (s3a & s3b) ^ (s3c & s3d) ^ s3e;
    wire [63:0] s4a = {x4[52:0], x4[63:53]};
    wire [63:0] s4b = {x4[40:0], x4[63:41]};
    wire [63:0] s4c = {x4[62:0], x4[63:63]};
    wire [63:0] s4d = {x4[61:0], x4[63:62]};
    wire [63:0] s4e = {x4[26:0], x4[63:27]};
    wire [63:0] x5 = x4 ^ (s4a & s4b) ^ (s4c & s4d) ^ s4e;
    wire [63:0] kr = {key[50:0], key[63:51]};
    assign out = x5 ^ kr;
endmodule
