/* r25_spn_pba19_sb_rasd3c2_27_513_nw: Broad S-box screen: 4r SPN, rasD3C2_27 (012347c9adbe65f8), pba19, L=lin(5,13), golden ks.
 * GENERATED by round25/gen_r25.py -- do not edit by hand.
 * Bit-exact vs Python model round25/models/r25.py (r25_spn_pba19_sb_rasd3c2_27_513_nw). */
#include <stdint.h>

static const uint8_t SBOXT[16] = {0,1,2,3,4,7,12,9,10,13,11,14,6,5,15,8};

static uint64_t rotl64(uint64_t x, unsigned r) {
    r &= 63u;
    return r ? (x << r) | (x >> (64u - r)) : x;
}
static uint64_t rk64(uint64_t k, int i) { /* i 0-based; ks=golden */
    static const uint64_t RC[4] = {0x9E3779B97F4A7C15ULL, 0x3C6EF372FE94F82AULL, 0xDAA66D2C7DDF743FULL, 0x78DDE6E5FD29F054ULL};
    unsigned r = (13u * (unsigned)(i + 1)) & 63u;
    return rotl64(k, r) ^ RC[i];
}
static uint64_t sbox64(uint64_t x) {
    uint64_t r = 0;
    for (int i = 0; i < 16; i++)
        r |= (uint64_t)SBOXT[(x >> (4*i)) & 0xFu] << (4*i);
    return r;
}
static uint64_t pbox64(uint64_t x) {
    uint64_t y = 0;
        y |= ((x >> 0) & 1u) << 1;
        y |= ((x >> 1) & 1u) << 20;
        y |= ((x >> 2) & 1u) << 39;
        y |= ((x >> 3) & 1u) << 58;
        y |= ((x >> 4) & 1u) << 13;
        y |= ((x >> 5) & 1u) << 32;
        y |= ((x >> 6) & 1u) << 51;
        y |= ((x >> 7) & 1u) << 6;
        y |= ((x >> 8) & 1u) << 25;
        y |= ((x >> 9) & 1u) << 44;
        y |= ((x >> 10) & 1u) << 63;
        y |= ((x >> 11) & 1u) << 18;
        y |= ((x >> 12) & 1u) << 37;
        y |= ((x >> 13) & 1u) << 56;
        y |= ((x >> 14) & 1u) << 11;
        y |= ((x >> 15) & 1u) << 30;
        y |= ((x >> 16) & 1u) << 49;
        y |= ((x >> 17) & 1u) << 4;
        y |= ((x >> 18) & 1u) << 23;
        y |= ((x >> 19) & 1u) << 42;
        y |= ((x >> 20) & 1u) << 61;
        y |= ((x >> 21) & 1u) << 16;
        y |= ((x >> 22) & 1u) << 35;
        y |= ((x >> 23) & 1u) << 54;
        y |= ((x >> 24) & 1u) << 9;
        y |= ((x >> 25) & 1u) << 28;
        y |= ((x >> 26) & 1u) << 47;
        y |= ((x >> 27) & 1u) << 2;
        y |= ((x >> 28) & 1u) << 21;
        y |= ((x >> 29) & 1u) << 40;
        y |= ((x >> 30) & 1u) << 59;
        y |= ((x >> 31) & 1u) << 14;
        y |= ((x >> 32) & 1u) << 33;
        y |= ((x >> 33) & 1u) << 52;
        y |= ((x >> 34) & 1u) << 7;
        y |= ((x >> 35) & 1u) << 26;
        y |= ((x >> 36) & 1u) << 45;
        y |= ((x >> 37) & 1u) << 0;
        y |= ((x >> 38) & 1u) << 19;
        y |= ((x >> 39) & 1u) << 38;
        y |= ((x >> 40) & 1u) << 57;
        y |= ((x >> 41) & 1u) << 12;
        y |= ((x >> 42) & 1u) << 31;
        y |= ((x >> 43) & 1u) << 50;
        y |= ((x >> 44) & 1u) << 5;
        y |= ((x >> 45) & 1u) << 24;
        y |= ((x >> 46) & 1u) << 43;
        y |= ((x >> 47) & 1u) << 62;
        y |= ((x >> 48) & 1u) << 17;
        y |= ((x >> 49) & 1u) << 36;
        y |= ((x >> 50) & 1u) << 55;
        y |= ((x >> 51) & 1u) << 10;
        y |= ((x >> 52) & 1u) << 29;
        y |= ((x >> 53) & 1u) << 48;
        y |= ((x >> 54) & 1u) << 3;
        y |= ((x >> 55) & 1u) << 22;
        y |= ((x >> 56) & 1u) << 41;
        y |= ((x >> 57) & 1u) << 60;
        y |= ((x >> 58) & 1u) << 15;
        y |= ((x >> 59) & 1u) << 34;
        y |= ((x >> 60) & 1u) << 53;
        y |= ((x >> 61) & 1u) << 8;
        y |= ((x >> 62) & 1u) << 27;
        y |= ((x >> 63) & 1u) << 46;
    return y;
}
static uint64_t lin_spec(uint64_t x) {
    return x ^ rotl64(x, 5) ^ rotl64(x, 13);
}
uint64_t mix_hash(uint64_t val, uint64_t key) {
    uint64_t x = val;
    for (int i = 0; i < 4; i++) {
        uint64_t t = sbox64(x ^ rk64(key, i));
        x = lin_spec(pbox64(t));
    }
    return x;
}
