// al_and9c: 6-stage AND-rotation cascade (generated by Track 3 wave-9)
module al_and9c(
    input [63:0] val,
    input [63:0] key,
    output [63:0] out
);
    wire [63:0] x0 = val ^ key;
    wire [63:0] s0a = {x0[62:0], x0[63:63]};
    wire [63:0] s0b = {x0[59:0], x0[63:60]};
    wire [63:0] s0c = {x0[46:0], x0[63:47]};
    wire [63:0] x1 = x0 ^ (s0a & s0b) ^ s0c;
    wire [63:0] s1a = {x1[61:0], x1[63:62]};
    wire [63:0] s1b = {x1[52:0], x1[63:53]};
    wire [63:0] s1c = {x1[56:0], x1[63:57]};
    wire [63:0] x2 = x1 ^ (s1a & s1b) ^ s1c;
    wire [63:0] s2a = {x2[58:0], x2[63:59]};
    wire [63:0] s2b = {x2[44:0], x2[63:45]};
    wire [63:0] s2c = {x2[40:0], x2[63:41]};
    wire [63:0] x3 = x2 ^ (s2a & s2b) ^ s2c;
    wire [63:0] s3a = {x3[56:0], x3[63:57]};
    wire [63:0] s3b = {x3[40:0], x3[63:41]};
    wire [63:0] s3c = {x3[52:0], x3[63:53]};
    wire [63:0] x4 = x3 ^ (s3a & s3b) ^ s3c;
    wire [63:0] s4a = {x4[52:0], x4[63:53]};
    wire [63:0] s4b = {x4[26:0], x4[63:27]};
    wire [63:0] s4c = {x4[58:0], x4[63:59]};
    wire [63:0] x5 = x4 ^ (s4a & s4b) ^ s4c;
    wire [63:0] s5a = {x5[50:0], x5[63:51]};
    wire [63:0] s5b = {x5[22:0], x5[63:23]};
    wire [63:0] s5c = {x5[44:0], x5[63:45]};
    wire [63:0] x6 = x5 ^ (s5a & s5b) ^ s5c;
    wire [63:0] kr = {key[50:0], key[63:51]};
    assign out = x6 ^ kr;
endmodule
