"""Synthesis runner: mirrors ~/workspace/mix/synth/synth_fast.ys EXACTLY.

Flow per design:
  read_verilog SRC
  hierarchy -check -top TOP
  proc; opt; flatten; opt
  memory_map; opt          # BEFORE techmap: ROM/mux inference must be
  techmap; opt             # techmapped to gates, else abc leaves unmapped
  abc -genlib mini.genlib  # muxes that never see techmap (silent area/delay
  opt; clean               # undercount in the analyzer)
  stat
  write_verilog -noattr mapped_TOP.v
then analyze.py AND analyze2.py (hardened cross-check); the two must agree.

Vendored from exploration/run_synth.py for the GitHub-Actions offload.
ONLY differences vs the on-VM original:
  - paths resolve relative to this file's directory (no /home/hatch hardcodes)
  - Yosys binary from $YOSYS_BIN (default: the on-VM pinned path, used only
    when running on the VM; the Docker image sets YOSYS_BIN=/opt/conda/bin/yosys)
Everything else (flow order, version assert, dual-analyzer cross-check,
RESULT line format) is byte-identical in behavior.

Usage: python3 run_synth.py <verilog> <top> <workdir>
Prints a one-line RESULT record. Also measures the mul64.v reference fresh
and reports ratios.
"""
import os, re, subprocess, sys

FLOW = os.path.dirname(os.path.abspath(__file__))
GENLIB = os.path.join(FLOW, "mini.genlib")
REF_V = os.path.join(FLOW, "mul64.v")
ANALYZE1 = os.path.join(FLOW, "analyze.py")
ANALYZE2 = os.path.join(FLOW, "analyze2.py")

# PINNED TOOLCHAIN (2026-10-02): bare "yosys" resolves via PATH and silently
# picked up /usr/bin/yosys 0.33 instead of the conda 0.69, producing different
# delay numbers for identical RTL (78.3u vs 56.5u). Always use $YOSYS_BIN and
# assert the version before synthesizing.
YOSYS = os.environ.get(
    "YOSYS_BIN", "/home/hatch/tools/micromamba-root/envs/sky130/bin/yosys")
YOSYS_WANT = "0.69"

YS_TMPL = """# Auto-generated by flow/run_synth.py -- mirrors synth_fast.ys
read_verilog {src}
hierarchy -check -top {top}
proc; opt; flatten; opt
memory_map; opt
techmap; opt
abc -genlib {genlib}
opt; clean
stat
write_verilog -noattr {mapped}
"""


def parse_analyze(out):
    m = re.search(r"cells:\s*(\d+)\s+total_area:\s*([\d.]+)\s+critical_path:\s*([\d.]+)", out)
    assert m, f"could not parse analyzer output:\n{out}"
    return dict(cells=int(m.group(1)), area=float(m.group(2)), crit=float(m.group(3)))


def synth_one(src, top, workdir):
    workdir = os.path.abspath(workdir)
    os.makedirs(workdir, exist_ok=True)
    src = os.path.abspath(src)
    mapped = os.path.join(workdir, f"mapped_{top}.v")
    ys = os.path.join(workdir, f"s_{top}.ys")
    with open(ys, "w") as f:
        f.write(YS_TMPL.format(src=src, top=top, genlib=GENLIB, mapped=mapped))
    vv = subprocess.run([YOSYS, "-V"], capture_output=True, text=True, timeout=60)
    if YOSYS_WANT not in (vv.stdout + vv.stderr):
        raise RuntimeError(f"wrong yosys at {YOSYS}: want {YOSYS_WANT}, got {(vv.stdout+vv.stderr)[:120]}")
    r = subprocess.run([YOSYS, "-s", ys], capture_output=True, text=True,
                       cwd=workdir, timeout=900)
    if r.returncode != 0 or not os.path.exists(mapped):
        raise RuntimeError(f"yosys failed for {top}:\n{r.stdout[-3000:]}\n{r.stderr[-3000:]}")
    a1 = subprocess.run([sys.executable, ANALYZE1,
                         mapped, GENLIB], capture_output=True, text=True, timeout=300)
    a2 = subprocess.run([sys.executable, ANALYZE2,
                         mapped, GENLIB], capture_output=True, text=True, timeout=300)
    if a1.returncode != 0:
        raise RuntimeError(f"analyze.py failed for {top}:\n{a1.stderr[-2000:]}")
    if a2.returncode != 0:
        raise RuntimeError(f"analyze2.py FAILED for {top} (not trusted):\n"
                           f"stdout={a2.stdout[-2000:]}\nstderr={a2.stderr[-2000:]}")
    r1, r2 = parse_analyze(a1.stdout), parse_analyze(a2.stdout)
    if abs(r1["crit"] - r2["crit"]) > 1e-6 or abs(r1["area"] - r2["area"]) > 1e-6 \
            or r1["cells"] != r2["cells"]:
        raise RuntimeError(f"analyzer MISMATCH for {top}: {r1} vs {r2}")
    return r1


def main():
    src, top, workdir = sys.argv[1], sys.argv[2], sys.argv[3]
    ref = synth_one(REF_V, "mul64", os.path.join(workdir, "_ref"))
    dut = synth_one(src, top, os.path.join(workdir, "_dut"))
    rd = dut["crit"] / ref["crit"]
    ra = dut["area"] / ref["area"]
    print(f"REF mul64: cells={ref['cells']} area={ref['area']:.0f} crit={ref['crit']:.1f}")
    print(f"DUT {top}: cells={dut['cells']} area={dut['area']:.0f} crit={dut['crit']:.1f}")
    print(f"RESULT name={top} cells={dut['cells']} area={dut['area']:.0f} "
          f"crit={dut['crit']:.1f} delay_ratio={rd:.3f} area_ratio={ra:.3f} "
          f"ref_crit={ref['crit']:.1f} ref_area={ref['area']:.0f}")
    print(f"XCHECK: analyze.py == analyze2.py (cells/area/crit identical)")


if __name__ == "__main__":
    main()
