// hyb18_dual_c: 5-stage [and,and,and,and,dual]: cheapest dual-last-stage, proxy z=8.0, est 18.40u (generated by hybrid/batch18/gen_batch18.py)
#include <stdint.h>
static inline uint64_t rotl64(uint64_t x, int r) {
    r &= 63;
    return r ? (x << r) | (x >> (64 - r)) : x;
}
uint64_t mix_hash(uint64_t val, uint64_t key) {
    uint64_t x = val ^ key;
    { /* AND stage 0 */
        uint64_t ra=rotl64(x,59),rb=rotl64(x,15),rc=rotl64(x,57);
        x ^= (ra & rb) ^ rc;
    }
    { /* AND stage 1 */
        uint64_t ra=rotl64(x,18),rb=rotl64(x,12),rc=rotl64(x,6);
        x ^= (ra & rb) ^ rc;
    }
    { /* AND stage 2 */
        uint64_t ra=rotl64(x,37),rb=rotl64(x,49),rc=rotl64(x,53);
        x ^= (ra & rb) ^ rc;
    }
    { /* AND stage 3 */
        uint64_t ra=rotl64(x,20),rb=rotl64(x,41),rc=rotl64(x,40);
        x ^= (ra & rb) ^ rc;
    }
    { /* DUAL stage 4 */
        uint64_t ra=rotl64(x,39),rb=rotl64(x,63),rc=rotl64(x,2),rd=rotl64(x,11),re=rotl64(x,50);
        x ^= (ra & rb) ^ (rc & rd) ^ re;
    }
    return x ^ rotl64(key, 13);
}
