"""hyb18_dual_c: 5-stage [and,and,and,and,dual]: cheapest dual-last-stage, proxy z=8.0, est 18.40u (generated by hybrid/batch18/gen_batch18.py)"""
import numpy as np
M64=np.uint64(0xFFFFFFFFFFFFFFFF)
def rotl(x,r):
    r%=64
    return ((x<<np.uint64(r))|(x>>np.uint64(64-r)))&M64 if r else x
STAGES=[['and', 59, 15, 57], ['and', 18, 12, 6], ['and', 37, 49, 53], ['and', 20, 41, 40], ['dual', 39, 63, 2, 11, 50]]
def apply_stage(x,st):
    t=st[0]
    if t=='and':
        _,a,b,c=st; return (x^(rotl(x,a)&rotl(x,b))^rotl(x,c))&M64
    if t=='t3':
        _,a,b,c,e=st; return (x^(rotl(x,a)&rotl(x,b))^rotl(x,c)^rotl(x,e))&M64
    if t=='dual':
        _,a,b,c,dd,e=st; return (x^(rotl(x,a)&rotl(x,b))^(rotl(x,c)&rotl(x,dd))^rotl(x,e))&M64
    raise ValueError(st)
def mix_hash(val,key):
    x=np.uint64(val)^np.uint64(key)
    for st in STAGES:
        x=apply_stage(x,st)
    return int((x^rotl(np.uint64(key),13))&M64)
