// hyb18_dual_c: 5-stage [and,and,and,and,dual]: cheapest dual-last-stage, proxy z=8.0, est 18.40u (generated by hybrid/batch18/gen_batch18.py)
module mix_hash(input [63:0] val, input [63:0] key, output [63:0] out);
    wire [63:0] x0 = val ^ key;
    wire [63:0] x1_ra = {x0[4:0], x0[63:5]};
    wire [63:0] x1_rb = {x0[48:0], x0[63:49]};
    wire [63:0] x1_rc = {x0[6:0], x0[63:7]};
    wire [63:0] x1 = x0 ^ (x1_ra & x1_rb) ^ x1_rc;
    wire [63:0] x2_ra = {x1[45:0], x1[63:46]};
    wire [63:0] x2_rb = {x1[51:0], x1[63:52]};
    wire [63:0] x2_rc = {x1[57:0], x1[63:58]};
    wire [63:0] x2 = x1 ^ (x2_ra & x2_rb) ^ x2_rc;
    wire [63:0] x3_ra = {x2[26:0], x2[63:27]};
    wire [63:0] x3_rb = {x2[14:0], x2[63:15]};
    wire [63:0] x3_rc = {x2[10:0], x2[63:11]};
    wire [63:0] x3 = x2 ^ (x3_ra & x3_rb) ^ x3_rc;
    wire [63:0] x4_ra = {x3[43:0], x3[63:44]};
    wire [63:0] x4_rb = {x3[22:0], x3[63:23]};
    wire [63:0] x4_rc = {x3[23:0], x3[63:24]};
    wire [63:0] x4 = x3 ^ (x4_ra & x4_rb) ^ x4_rc;
    wire [63:0] x5_ra = {x4[24:0], x4[63:25]};
    wire [63:0] x5_rb = {x4[0:0], x4[63:1]};
    wire [63:0] x5_rc = {x4[61:0], x4[63:62]};
    wire [63:0] x5_rd = {x4[52:0], x4[63:53]};
    wire [63:0] x5_re = {x4[13:0], x4[63:14]};
    wire [63:0] x5 = x4 ^ (x5_ra & x5_rb) ^ (x5_rc & x5_rd) ^ x5_re;
    assign out = x5 ^ {key[50:0], key[63:51]};
endmodule
