// al_chi6g: 6-stage chi cascade, avalanche-aware schedule G (random well-separated) (generated by gen_wave1.py)
module al_chi6g(
    input [63:0] val,
    input [63:0] key,
    output [63:0] out
);
    wire [63:0] x0 = val ^ key;
    wire [63:0] s0a = {x0[32:0], x0[63:33]};
    wire [63:0] s0b = {x0[62:0], x0[63:63]};
    wire [63:0] s0c = {x0[19:0], x0[63:20]};
    wire [63:0] x1 = x0 ^ ((~s0a) & s0b) ^ s0c;
    wire [63:0] s1a = {x1[59:0], x1[63:60]};
    wire [63:0] s1b = {x1[35:0], x1[63:36]};
    wire [63:0] s1c = {x1[29:0], x1[63:30]};
    wire [63:0] x2 = x1 ^ ((~s1a) & s1b) ^ s1c;
    wire [63:0] s2a = {x2[58:0], x2[63:59]};
    wire [63:0] s2b = {x2[0:0], x2[63:1]};
    wire [63:0] s2c = {x2[23:0], x2[63:24]};
    wire [63:0] x3 = x2 ^ ((~s2a) & s2b) ^ s2c;
    wire [63:0] s3a = {x3[43:0], x3[63:44]};
    wire [63:0] s3b = {x3[49:0], x3[63:50]};
    wire [63:0] s3c = {x3[21:0], x3[63:22]};
    wire [63:0] x4 = x3 ^ ((~s3a) & s3b) ^ s3c;
    wire [63:0] s4a = {x4[55:0], x4[63:56]};
    wire [63:0] s4b = {x4[24:0], x4[63:25]};
    wire [63:0] s4c = {x4[8:0], x4[63:9]};
    wire [63:0] x5 = x4 ^ ((~s4a) & s4b) ^ s4c;
    wire [63:0] s5a = {x5[18:0], x5[63:19]};
    wire [63:0] s5b = {x5[2:0], x5[63:3]};
    wire [63:0] s5c = {x5[42:0], x5[63:43]};
    wire [63:0] x6 = x5 ^ ((~s5a) & s5b) ^ s5c;
    wire [63:0] kr = {key[50:0], key[63:51]};
    assign out = x6 ^ kr;
endmodule
