// al_dualand5b: Wave-10: 5-stage dual-AND, fresh schedule (floor attack, independent) (generated by gen_wave1.py)
module al_dualand5b(
    input [63:0] val,
    input [63:0] key,
    output [63:0] out
);
    wire [63:0] x0 = val ^ key;
    wire [63:0] s0a = {x0[61:0], x0[63:62]};
    wire [63:0] s0b = {x0[54:0], x0[63:55]};
    wire [63:0] s0c = {x0[40:0], x0[63:41]};
    wire [63:0] s0d = {x0[22:0], x0[63:23]};
    wire [63:0] s0e = {x0[50:0], x0[63:51]};
    wire [63:0] x1 = x0 ^ (s0a & s0b) ^ (s0c & s0d) ^ s0e;
    wire [63:0] s1a = {x1[58:0], x1[63:59]};
    wire [63:0] s1b = {x1[46:0], x1[63:47]};
    wire [63:0] s1c = {x1[32:0], x1[63:33]};
    wire [63:0] s1d = {x1[10:0], x1[63:11]};
    wire [63:0] s1e = {x1[56:0], x1[63:57]};
    wire [63:0] x2 = x1 ^ (s1a & s1b) ^ (s1c & s1d) ^ s1e;
    wire [63:0] s2a = {x2[52:0], x2[63:53]};
    wire [63:0] s2b = {x2[34:0], x2[63:35]};
    wire [63:0] s2c = {x2[60:0], x2[63:61]};
    wire [63:0] s2d = {x2[44:0], x2[63:45]};
    wire [63:0] s2e = {x2[20:0], x2[63:21]};
    wire [63:0] x3 = x2 ^ (s2a & s2b) ^ (s2c & s2d) ^ s2e;
    wire [63:0] s3a = {x3[50:0], x3[63:51]};
    wire [63:0] s3b = {x3[26:0], x3[63:27]};
    wire [63:0] s3c = {x3[56:0], x3[63:57]};
    wire [63:0] s3d = {x3[38:0], x3[63:39]};
    wire [63:0] s3e = {x3[58:0], x3[63:59]};
    wire [63:0] x4 = x3 ^ (s3a & s3b) ^ (s3c & s3d) ^ s3e;
    wire [63:0] s4a = {x4[44:0], x4[63:45]};
    wire [63:0] s4b = {x4[16:0], x4[63:17]};
    wire [63:0] s4c = {x4[52:0], x4[63:53]};
    wire [63:0] s4d = {x4[30:0], x4[63:31]};
    wire [63:0] s4e = {x4[46:0], x4[63:47]};
    wire [63:0] x5 = x4 ^ (s4a & s4b) ^ (s4c & s4d) ^ s4e;
    wire [63:0] kr = {key[50:0], key[63:51]};
    assign out = x5 ^ kr;
endmodule
