// fz13_het5b: generated by gen_fused13.py
module fz13_het5b(
    input  wire [63:0] v,
    input  wire [63:0] k,
    output wire [63:0] out
);
    function [63:0] rotl;
        input [63:0] x;
        input integer r;
        begin
            r = r % 64;
            rotl = r ? ((x << r) | (x >> (64 - r))) : x;
        end
    endfunction
    wire [63:0] x0 = v ^ k;
    wire [63:0] r0_3 = rotl(x0, 3);
    wire [63:0] r0_11 = rotl(x0, 11);
    wire [63:0] r0_29 = rotl(x0, 29);
    wire [63:0] x1 = (x0 ^ (r0_3 & r0_11) ^ r0_29);
    wire [63:0] r1_5 = rotl(x1, 5);
    wire [63:0] r1_7 = rotl(x1, 7);
    wire [63:0] r1_19 = rotl(x1, 19);
    wire [63:0] x2 = (x1 ^ ((r1_7 & r1_19) | (r1_7 & r1_5) | (r1_19 & r1_5)));
    wire [63:0] r2_1 = rotl(x2, 1);
    wire [63:0] r2_2 = rotl(x2, 2);
    wire [63:0] r2_13 = rotl(x2, 13);
    wire [63:0] x3 = (x2 ^ (r2_1 & r2_2) ^ r2_13);
    wire [63:0] r3_7 = rotl(x3, 7);
    wire [63:0] r3_17 = rotl(x3, 17);
    wire [63:0] r3_31 = rotl(x3, 31);
    wire [63:0] x4 = (x3 ^ (r3_17 & r3_31) ^ r3_7);
    wire [63:0] r4_11 = rotl(x4, 11);
    wire [63:0] r4_23 = rotl(x4, 23);
    wire [63:0] r4_37 = rotl(x4, 37);
    wire [63:0] x5 = (x4 ^ (r4_11 & r4_23) ^ r4_37);
    wire [63:0] k13 = rotl(k, 13);
    assign out = x5 ^ k13;
endmodule
